- README.md
- ROADMAP.md
Fixed inconsistencies in punctuation within the README.md and ROADMAP.md files.
> Update README.md and ROADMAP.md

- docs/create-a-note-in-notesnook.md
> Improvements to documentation

- README.md
Signed-off-by: Tushar Raj <tusharraj.1728@gmail.com>
> docs: used relative links and fixed typos

- CODE_OF_CONDUCT.md
docs: add changes suggested by npm lint
Signed-off-by: Tushar Raj <43772524+tushar-1728@users.noreply.github.com>
> docs: add changes suggested by npm lint

- apps/web/desktop/autoupdate.js
- apps/web/desktop/package-lock.json
- apps/web/desktop/package.json
- apps/web/package-lock.json
- apps/web/package.json
- apps/web/src/common/dialog-controller.tsx
- apps/web/src/hooks/use-auto-updater.js
- apps/web/src/utils/changelog.ts
- apps/web/src/utils/version.ts
> Open all links in release notes in a new tab/window

- packages/core/database/migrator.js
> Fixed "Unknown content type" error on backup restore

- apps/web/src/components/editor/title-box.tsx
this was a subtle bug where typing really fast in the editor caused jank & erratic behavior.
> Fix issue where typing really fast in title input caused jank

- apps/web/desktop/package.json
> Fix issue with snap desktop integration

- apps/web/desktop/package.json
> Reduce minimum required macOS version to 10.12.0

- apps/web/src/components/editor/tiptap.tsx
> Clicking under table should create a new paragraph

- apps/web/src/components/editor/header.js
- packages/core/api/lookup.js
- packages/core/collections/tags.js
- packages/core/models/note.js
> Fix issue where free users could not assign already created tags

- apps/web/src/components/editor/index.tsx
- packages/editor/src/extensions/table/component.tsx
> Fix issue where table row toolbar would get clipped on smaller screens

- apps/web/src/components/editor/title-box.tsx
This will allow easier viewing of really long titles.
> Make editor title font-size relative to title length

- apps/mobile/app/components/list-items/selection-wrapper/selection.js
- apps/mobile/app/components/selection-header/index.js
- apps/mobile/app/components/sheets/export-notes/index.js
- apps/mobile/app/hooks/use-actions.js
- apps/mobile/app/package.json
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/services/exporter.js
- apps/mobile/app/services/premium.js
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/mobile/package.json
- apps/web/src/views/settings.js
- packages/core/collections/notes.js
Bulk exporting PDF is not yet supported. Locked notes will also not be exported.
> Allow exporting all notes as html, md or txt

- apps/mobile/app/components/sheets/migrate/index.tsx
Migration will happen automatically on app launch if user input is not required.
> Automate migration when possible

- apps/mobile/app/components/sheet-provider/index.js
- apps/mobile/app/components/sheets/export-notes/index.js
Export sheet is closable during bulk exports
> Fix export sheeet closable

- apps/mobile/app/components/list-items/notebook/index.js
- apps/mobile/app/components/list-items/notebook/wrapper.js
- apps/mobile/app/components/list/index.js
- apps/mobile/app/screens/notes/common.ts
- apps/mobile/app/services/navigation.ts
- apps/mobile/app/utils/index.js
Total notes on topic and notebook did not update when creating a new note inside a topic due to bug in routes update queue.
> mobile: fix total notes not updated on notebook

- packages/core/database/cached-collection.js
This fixes #1231
This fixes #1230
This fixes #1235
This fixes #1224
> Fix null is not an object error

- apps/web/package-lock.json
- apps/web/package.json
- apps/web/src/app-effects.js
- apps/web/src/common/reminders.js
- apps/web/src/utils/task-scheduler.ts
- apps/web/src/utils/task-scheduler.worker.ts
- apps/web/src/views/settings.js
This will increase backup reliability since before backups happened either at app startup or after successful sync. This could create the issue where backups would not be created regularly. This new scheduler based implementation fixes this by scheduling automatic backups according to user's settings.
> Schedule automatic backups

- packages/editor/src/extensions/code-block/component.tsx
- packages/editor/src/extensions/code-block/highlighter.ts
- packages/editor/src/extensions/react/react-node-view.tsx
- packages/editor/src/extensions/react/selection-based-react-node-view.tsx
- packages/editor/src/extensions/react/types.ts
> editor: desktop editor refresh code block

- packages/editor/src/extensions/search-replace/search-replace.ts
> editor: search occurence scroll into view corrected

- packages/editor/src/extensions/clipboard-text-serializer/index.ts
> Fix incorrect paragraph formatting while copying text from editor

- packages/core/database/backup.js
- packages/core/database/migrator.js
> Fix issue where latest backups are not restored

- apps/mobile/app/components/list-items/note/wrapper.js
- apps/mobile/app/components/note-history/preview.js
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/web/src/components/editor/toolbar.js
- apps/web/src/components/trash-item/index.js
- apps/web/src/stores/editor-store.js
- packages/core/collections/notes.js
> Preview notes in trash

- apps/web/src/views/settings.js
> desktop: show backup location button

- packages/editor/src/components/popup-presenter/index.tsx
- packages/editor/src/toolbar/components/more-tools.tsx
- packages/editor/src/toolbar/components/split-button.tsx
- packages/editor/src/toolbar/icons.ts
- packages/editor/src/toolbar/popups/color-picker.tsx
- packages/editor/src/toolbar/tools/colors.tsx
- packages/editor/src/toolbar/tools/lists.tsx
> Add support for saving custom colors in editor color picker

- packages/core/utils/grouping.js
> core: sort numbered notes properly

- apps/web/src/components/dialogs/toolbar-config-dialog.tsx
> web: bug removed in config toolbar dialog when trashing items

- packages/core/models/note.js
- packages/core/utils/templates/helper.js
- packages/core/utils/templates/html/template.js
- packages/core/utils/templates/markdown/template.js
- packages/core/utils/templates/text/template.js
> core: added tags in export

- packages/editor/src/extensions/list-item/commands.ts
- packages/editor/src/extensions/task-list/component.tsx
- packages/editor/src/toolbar/icons.ts
> Add button to clear completed tasks

- apps/web/src/components/list-item/index.js
> web: notes selection issue on right click

- packages/core/collections/attachments.js
> Fix issue with deleting attachments permanently

- apps/web/src/app.js
- apps/web/src/components/scroll-container/index.tsx
> desktop: style bottom scrollbar in mobile mode

- apps/web/src/views/settings.js
> Fix overlapping text on default home page buttons in settings

- packages/editor/src/index.ts
- packages/editor/src/toolbar/stores/toolbar-store.ts
> Fix persistent editor dropdown toolbar even when changing notes

- packages/editor/src/extensions/task-list/component.tsx
> Fix clear completed tasks button hidden by progress bar

- apps/web/src/components/list-container/index.tsx
- apps/web/src/components/list-item/index.js
- apps/web/src/hooks/use-keyboard-list-navigation.ts
- apps/web/src/stores/selection-store.js
> web: ctrl+click select unselect corrected

- packages/editor/src/extensions/task-item/component.tsx
- packages/editor/src/extensions/task-item/task-item.ts
- packages/editor/src/extensions/task-list/component.tsx
> editor: feature added. Delete task list item

- packages/editor/src/extensions/task-item/component.tsx
- packages/editor/src/extensions/task-list/component.tsx
> editor: disable deleting completd tasks in read mode

- apps/web/__e2e__/keyboard-list-navigation.test.ts
> web: ctrl click selection tests

- packages/editor/src/components/popup-presenter/index.tsx
> Fix issue where text highlight & text color popups were not opening on mobile

- packages/editor/src/extensions/task-item/task-item.ts
- packages/editor/src/extensions/task-list/component.tsx
- packages/editor/src/extensions/task-list/task-list.ts
> editor: collapse item feature removed completely

- apps/mobile/app/common/database/index.js
- apps/mobile/app/components/auth/forgot-password.js
- apps/mobile/app/components/sheets/change-email/index.tsx
- apps/mobile/app/components/ui/sheet/index.js
- apps/mobile/app/screens/notes/common.ts
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/utils/color-scheme/index.js
- apps/web/src/common/dialog-controller.tsx
- apps/web/src/components/dialogs/email-change-dialog.tsx
- apps/web/src/components/dialogs/index.ts
- apps/web/src/components/field/index.js
- apps/web/src/views/settings.js
- packages/core/api/index.js
- packages/core/api/user-manager.js
> Add support for changing account email

- apps/web/desktop/electron.js
> Show app name on notifications in windows

- apps/web/desktop/electron.js
- packages/core/api/index.js
- packages/core/api/sync/index.js
> Don't connect SSE or run sync when user is logged out

- apps/web/desktop/config/spellChecker.js
- apps/web/desktop/config/theme.js
- apps/web/desktop/electron.js
- apps/web/desktop/global.d.ts
- apps/web/desktop/ipc/actions/bringToFront.js
- apps/web/desktop/ipc/actions/changeAppTheme.js
- apps/web/desktop/ipc/actions/index.js
- apps/web/desktop/ipc/actions/setPrivacyMode.js
- apps/web/desktop/ipc/actions/setSpellCheckerLanguages.js
- apps/web/desktop/ipc/actions/setZoomFactor.js
- apps/web/desktop/ipc/actions/showNotification.js
- apps/web/desktop/ipc/actions/toggleSpellChecker.js
- apps/web/desktop/ipc/calls/getSpellChecker.js
- apps/web/desktop/ipc/utils.js
- apps/web/desktop/jsonstorage/index.js
- apps/web/desktop/menu.js
- apps/web/desktop/preload.js
- apps/web/desktop/protocol.js
- apps/web/desktop/tsconfig.json
- apps/web/src/commands/set-spell-checker-languages.js
- apps/web/src/commands/toggle-spell-checker.js
- apps/web/src/common/dialog-controller.tsx
- apps/web/src/components/dialogs/index.ts
- apps/web/src/components/dialogs/language-selector-dialog.tsx
- apps/web/src/global.d.ts
- apps/web/src/hooks/use-spell-checker.ts
- apps/web/src/views/settings.js
This closes #404
I have added 2 new settings:
1. Enable/disable spell checker
2. Select spell checker languages
> Multi language spell check

- apps/web/src/components/editor/tiptap.tsx
> Don't create new p tag at editor end if there is selection

- packages/editor/src/toolbar/popups/search-replace.tsx
> Fix crash when closing search in a different note than the one it was opened in

- apps/web/__e2e__/reminders.test.ts
- apps/web/src/components/dialogs/add-reminder-dialog.tsx
> Do not reset reminder's recurring mode on edit

- apps/web/src/components/dialogs/add-reminder-dialog.tsx
> Fix issue where monthly recurring reminder was always 1 day behind

- apps/web/src/views/settings.js
> Reorder & invert sync toggles in settings

- apps/web/src/views/auth.tsx
> Recovery code input should accept alphanumeric input

- apps/mobile/app/components/selection-header/index.js
> mobile: improved multi-select

- apps/mobile/app/components/list-items/reminder/index.tsx
- apps/mobile/app/components/list/card.js
- apps/mobile/app/components/properties/index.js
- apps/mobile/app/components/sheets/reminder/index.tsx
- apps/mobile/app/components/ui/input/index.tsx
- apps/mobile/app/services/notifications.ts
- apps/web/src/components/dialogs/add-reminder-dialog.tsx
- apps/web/src/components/list-item/index.js
> mobile: reminder improvements

- apps/web/desktop/electron.js
- apps/web/src/components/dialogs/language-selector-dialog.tsx
> Fix start minimized on Windows

- apps/web/desktop/config/window-state.ts
- apps/web/desktop/electron.js
- apps/web/desktop/menu.js
- apps/web/desktop/tray.ts
Closes #1852
Closes #1831
Closes #1830
> Fix various issues with desktop integration on macOS

- apps/mobile/app/screens/notes/common.ts
> fix cannot read property of title

- apps/mobile/app/components/auth/two-factor.js
- apps/mobile/app/components/auth/use-login.js
Removed recovery code max length limit from input.
> Remove recovery code input maxLength

- apps/web/src/components/menu/index.js
- apps/web/src/components/menu/menu-item.js
> Fix issue where notebooks submenu is positioned incorrectly

- apps/mobile/app/app.js
- apps/mobile/app/services/notifications.ts
- apps/mobile/native/android/app/build.gradle
- apps/mobile/native/index.js
- apps/mobile/native/ios/Notesnook.xcodeproj/project.pbxproj
- apps/mobile/native/ios/Notesnook/AppDelegate.mm
- apps/mobile/native/ios/Podfile.lock
> mobile: fix background events

- apps/mobile/app/screens/settings/components.tsx
- apps/mobile/app/screens/settings/license-data.js
- apps/mobile/app/screens/settings/licenses.tsx
- apps/mobile/app/screens/settings/settings-data.tsx
Added licenses of open source libraries in mobile app
> mobile: add oss licenses

- apps/mobile/app/common/filesystem/compress.js
- apps/mobile/app/common/filesystem/io.js
- apps/mobile/app/screens/editor/index.tsx
- apps/mobile/app/screens/editor/tiptap/commands.ts
- apps/mobile/app/screens/editor/tiptap/picker.js
- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- apps/mobile/app/stores/use-user-store.ts
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/web/src/components/editor/index.tsx
- packages/core/collections/attachments.js
- packages/core/utils/event-manager.js
- packages/editor-mobile/src/components/styles.module.css
- packages/editor-mobile/src/components/tags.tsx
- Fixes #1990
- Adds image compression for loading images in editor to improve performance.
> Fix loading images in realtime sync

- apps/web/src/common/reminders.js
> Hide backup reminder on download backup

- apps/mobile/app/services/notifications.ts
- apps/mobile/native/android/app/build.gradle
- apps/mobile/native/ios/Notesnook.xcodeproj/project.pbxproj
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/mobile/package.json
Some manifest changes in the last release broke reminders on android. Closes #2036
> Fix reminders not working on android

- Changes.txt
- packages/theme/src/theme/variants/input.ts
Just fixed the caret color too..
> Search autocomplete text color

- packages/editor/src/toolbar/components/more-tools.tsx
- packages/editor/src/toolbar/icons.ts
- packages/editor/src/toolbar/tool-definitions.ts
- packages/editor/src/toolbar/tools/table.tsx
> Move cell properties button outside of table settings

- packages/editor/src/toolbar/components/dropdown.tsx
> Fix issue where dropdown required 2 clicks to open in editor toolbar

- packages/editor/src/extensions/image/image.ts
- packages/editor/src/utils/downloader.ts
- Add support for pasting images on ios into editor
- Fixed transaction mismatch error on paste image
Fixes #2092
> editor: fix loading of copied images on iOS

- apps/mobile/app/components/attachments/attachment-item.js
- apps/mobile/app/components/attachments/index.js
- apps/mobile/app/screens/editor/tiptap/picker.js
- apps/mobile/app/screens/settings/settings-data.tsx
> Fix gallery not shown when reupload image

- apps/web/src/components/diff-viewer/index.js
- apps/web/src/components/unlock/index.js
- packages/editor/package-lock.json
- packages/editor/package.json
- packages/editor/src/extensions/task-list/tests/__snapshots__/task-list.test.ts.snap
- packages/editor/src/extensions/task-list/tests/task-list.test.ts
- packages/editor/src/extensions/task-list/utils.ts
> Fix sub checklists not getting sorted

- apps/web/desktop/package.json
> Enable arm64 builds on Linux & Windows

- apps/web/src/components/search/index.js
> web: Added live search

- apps/web/src/common/dialog-controller.tsx
- apps/web/src/views/search.js
> Fix crash on topic create & topic search

- apps/web/src/app-effects.js
- apps/web/src/views/settings.js
> Fix auto backup & trash cleanup interval settings getting reset

- apps/web/src/utils/page-visibility.ts
Used any type at line 41 please review that..
> converted page visibility.js into typescript

- apps/mobile/app/components/sheets/reminder/index.tsx
- Fixes reminder date in date picker not set in past.
> mobile: fix reminder date picker not going in past

- apps/mobile/app/components/sheets/sort/index.js
- apps/mobile/app/components/sheets/topic-sheet/index.tsx
- apps/mobile/app/package.json
- apps/mobile/package-lock.json
- Add sorting topics in sheet
- Fixed initial height of sheet on ios
> Feat sort topics

- apps/mobile/app/screens/settings/section-item.tsx
Save snooze time value as user types.
Closes #2061
> Save snooze time value on change on user does not have to press enter

- packages/core/utils/templates/html/template.js
Issue: PDF issues with codeblocks and links #1661
> Fix code block overflow in PDF export

- apps/mobile/native/ios/Notesnook.xcodeproj/project.pbxproj
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/native/react-native.config.js
- apps/mobile/share/search.js
- apps/mobile/share/share.js
- apps/mobile/share/store.js
- Redesign share extension
- Adds support for tagging notes from Share
- Adds support for Adding notes to notebooks & topics.
> Support Organizing notes in Share Extension

- apps/web/src/utils/importer.ts
> web: fix `cannot read property id of undefined` on Import

- apps/mobile/app/hooks/use-actions.js
- apps/mobile/app/utils/index.js
- apps/web/src/common/export.ts
- packages/core/models/note.js
> Fix pin to notification text line spacing

- apps/mobile/app/components/list-items/note/index.js
- apps/mobile/app/components/list-items/note/wrapper.js
- apps/mobile/app/components/list/index.js
- apps/mobile/app/hooks/use-actions.js
> mobile: fix tag not updated on list item on rename

- README.md
docs: Updated grammar readme
Signed-off-by: Nick Thomas nick02@iastate.edu
> Updated grammar readme

- apps/mobile/app/components/list/index.js
> mobile: fix crash when data is null in list & jump to dialog is opened

- packages/core/collections/notes.js
> core: add remote note if local note does not exist

- apps/mobile/README.md
- apps/web/README.md
docs: Fixed grammar issues with the README files for both the app and the web directories.
Signed-off-by: Nedim Hodzic <hodzicnedim11@gmail.com>
> Update grammar app readmes

- apps/mobile/app/components/sheets/add-notebook/index.js
- apps/mobile/app/components/sheets/reminder/index.tsx
Redesigned add reminder/notebook sheets with Save button on top alongside title instead of at the bottom. Closes #2303
> mobile: redesign reminder/notebook sheets

- apps/mobile/app/services/notifications.ts
> mobile: fix crash when tap on notification and

- apps/mobile/app/package.json
- apps/mobile/native/webpack.config.cjs
- apps/mobile/package-lock.json
- apps/mobile/patches/leac+0.6.0.patch
- packages/core/content-types/tiptap.js
- packages/core/package-lock.json
> mobile: fix text exports

- packages/core/api/subscriptions.js
> Fix "Unauthorized" error on subscription cancelation & update

- packages/core/models/note.js
> core: deep clone note when duplicating

- packages/editor/src/toolbar/components/dropdown.tsx
> editor: fix toolbar dropdown buttons size on mobile

- apps/mobile/app/components/sheets/sort/index.js
- apps/mobile/app/screens/settings/editor/tool-sheet.tsx
> mobile: fix configure toolbar sheet close with swipe

- apps/mobile/app/components/properties/items.js
- apps/mobile/app/hooks/use-actions.js
> mobile: fix note options ui

- apps/mobile/app/services/notifications.ts
- apps/mobile/share/share.js
- apps/mobile/share/store.js
> Sync notes created from quick note/notification notes

- apps/mobile/app/components/properties/notebooks.js
> mobile: close editor on navigate to topic

- apps/mobile/app/screens/notebook/index.tsx
> mobile: fix crash on get search items

- apps/mobile/app/components/attachments/attachment-item.js
- apps/mobile/app/hooks/use-actions.js
- apps/mobile/app/hooks/use-attachment-progress.ts
Closes #2449 
Closes #2460
Closes #2461
> mobile: fix crash on attachment upload

- packages/core/collections/notes.js
> Fix issue where notes directly in a notebook could not be unlinked

- apps/mobile/app/app.js
- apps/mobile/app/services/notifications.ts
- apps/mobile/native/index.js
- apps/mobile/share/share.js
When offline skip syncing otherwise it can cause an indefinite loading on save.
> mobile: sync quick notes only when online

- apps/web/src/app-effects.js
- apps/web/src/app.js
- apps/web/src/utils/web-extension-relay.ts
- apps/web/src/utils/web-extension-server.ts
- extensions/web-clipper/build-utils/manifest.js
- extensions/web-clipper/src/api.ts
- extensions/web-clipper/src/common/bridge.ts
- extensions/web-clipper/src/content-scripts/nn.ts
this adds support for working with multiple Notesnook tabs even though it is not currently recommended that you open multiple Notesnook tabs
> Improve clipper connection reliability

- apps/web/src/utils/web-extension-server.ts
- extensions/web-clipper/src/common/bridge.ts
- extensions/web-clipper/src/components/check-list-item/index.tsx
- extensions/web-clipper/src/components/filtered-list/index.tsx
- extensions/web-clipper/src/components/icons/index.ts
- extensions/web-clipper/src/components/inline-tag/index.tsx
- extensions/web-clipper/src/components/note-picker/index.tsx
- extensions/web-clipper/src/components/notebook-picker/index.tsx
- extensions/web-clipper/src/components/picker/index.tsx
- extensions/web-clipper/src/components/tag-picker/index.tsx
- extensions/web-clipper/src/stores/app-store.tsx
- extensions/web-clipper/src/views/main.tsx
- packages/clipper/package.json
- packages/clipper/patches/css-what+6.1.0.patch
Merges fixes from #2048 & #2053
Closes #2488
Closes  #1904
Closes  #2099
Closes #2029
Closes #2006
Closes #1687
Closes #1673
Closes #1638
Closes #1602
Closes #1600
Closes #1475
> Web clipper 0.2

- apps/mobile/app/screens/editor/wrapper.js
> mobile: always check editor is ready on enter foreground

- apps/web/src/components/search/index.js
- apps/web/src/views/search.js
> Add support for search inside notebook

- apps/mobile/app/common/filesystem/download-attachment.js
- apps/mobile/app/components/attachments/download-attachments.js
> mobile: fix crash on download all attachement

- packages/editor/src/extensions/attachment/attachment.ts
- packages/editor/src/extensions/attachment/component.tsx
- packages/editor/src/extensions/react/selection-based-react-node-view.tsx
- packages/editor/src/extensions/react/types.ts
Issue: #2609 
Item solved
- Can not download attachments.
> editor: attachment download on Readonly

- apps/web/desktop/autolaunch.ts
- apps/web/desktop/cli.ts
- apps/web/desktop/electron.js
- apps/web/desktop/ipc/actions/setDesktopIntegration.js
- apps/web/desktop/tray.ts
> Fix start as minimized on Windows

- apps/mobile/app/common/database/encryption.js
- apps/mobile/app/common/filesystem/io.js
- apps/mobile/app/common/filesystem/upload.js
- apps/mobile/app/hooks/use-app-events.js
- apps/mobile/app/screens/editor/tiptap/picker.js
- apps/mobile/app/utils/constants.js
- apps/mobile/app/utils/note-bundle.js
- apps/mobile/native/android/app/src/main/AndroidManifest.xml
- apps/mobile/native/ios/Make Note/Info.plist
- apps/mobile/native/ios/Make Note/Make Note.entitlements
- apps/mobile/native/ios/Notesnook/Info.plist
- apps/mobile/native/ios/Notesnook/Notesnook.entitlements
- apps/mobile/native/ios/Notesnook/NotesnookDebug.entitlements
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/mobile/share/share.js
Added support for sharing images & files to Notesnook on Android & iOS.
> Add support for image & file sharing

- apps/mobile/app/components/list-items/note/index.js
- apps/mobile/app/components/list-items/selection-wrapper/index.js
- apps/mobile/app/components/list-items/selection-wrapper/selection.js
> mobile: increase compactness of compact mode

- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/global.d.ts
> Fix editor theme not changing with app theme

- apps/mobile/share/share.js
> mobile: fix appending link to empty note stuck

- apps/mobile/app/screens/editor/tiptap/types.ts
- apps/mobile/app/screens/editor/tiptap/use-editor-events.ts
- apps/mobile/app/screens/editor/tiptap/use-editor.ts
> Fix picking image or file replaces content if note is locked and app lock is enabled

- packages/core/collections/reminders.js
- packages/core/utils/date.js
> Fix incorrect snooze time format

- apps/mobile/app/screens/notebook/index.tsx
- apps/web/__e2e__/models/notes-view.model.ts
- apps/web/src/navigation/routes.jsx
- apps/web/src/views/search.jsx
> Fix search in topic/notebook return incomplete results

- apps/mobile/app/components/sheets/reminder/index.tsx
> date picker follow time format set in settings

- packages/editor/src/extensions/heading/heading.ts
- packages/editor/src/extensions/heading/index.ts
- packages/editor/src/extensions/text-direction/text-direction.ts
- packages/editor/src/index.ts
> Persist text alignment & direction on heading creation

- apps/web/src/app.jsx
> Fix pane sizes getting reset randomly on startup

- apps/web/src/components/editor/index.tsx
> Allow focusing editor by clicking at the bottom

- apps/web/src/components/diff-viewer/content-toggle.jsx
- apps/web/src/components/diff-viewer/index.jsx
> Fix crash on viewing a merge conflict

- packages/core/models/notebook.js
> Do not include trashed notes in total notebook notes

- apps/web/package-lock.json
- apps/web/package.json
- apps/web/vite.config.ts
- packages/editor/src/extensions/outline-list-item/outline-list-item.ts
> Fix black squares in outline lists

- apps/desktop/src/api/os-integration.ts
- apps/desktop/src/main.ts
- apps/desktop/src/utils/config.ts
- apps/web/src/common/dialog-controller.tsx
- apps/web/src/components/dialog/index.tsx
- apps/web/src/dialogs/index.ts
- apps/web/src/dialogs/settings/components/customize-toolbar.tsx
- apps/web/src/dialogs/settings/components/importer.tsx
- apps/web/src/dialogs/settings/components/spell-checker-languages.tsx
- apps/web/src/dialogs/settings/components/subscription-status.tsx
- apps/web/src/dialogs/settings/desktop-integration-settings.ts
- apps/web/src/dialogs/settings/editor-settings.ts
- apps/web/src/dialogs/settings/index.tsx
- apps/web/src/stores/setting-store.js
> Fix minor issues with new Settings

- apps/desktop/global.d.ts
- apps/desktop/package-lock.json
- apps/desktop/package.json
- apps/desktop/src/preload.ts
- apps/desktop/src/utils/protocol.ts
- apps/web/vite.config.ts
Closes #2789
Closes #2803
Closes #2807
> Fix desktop crash due to undici fetch

- packages/sodium/src/node.ts
> Fix 'c must be...' error when adding a big attachment

- apps/desktop/package-lock.json
- apps/web/package-lock.json
- apps/web/package.json
> Fix PDF attachments cannot be opened in editor

- apps/web/package-lock.json
- apps/web/package.json
- apps/web/src/utils/streams/attachment-stream.ts
- apps/web/src/utils/streams/zip-stream.ts
> Fix invalid zip error when downloading attachments in bulk

- packages/sodium/src/node.ts
> Fix error when downloading large attachments/images

- apps/web/src/dialogs/buy-dialog/buy-dialog.tsx
- apps/web/src/dialogs/settings/components/subscription-status.tsx
> Fix subscription plan not changing from monthly

- apps/mobile/app/screens/settings/picker/pickers.jsx
> Fix changing font family causes error

- packages/editor/src/toolbar/components/split-button.tsx
> editor: fix toolbar button alignment

- packages/core/collections/attachments.js
> Fix cannot re-insert an orphan image 

- packages/core/api/sync/index.js
Closes #2868
Closes #2394
Closes #2325 
Closes #2314
> Force upate token if email is already confirmed

- apps/mobile/app/stores/use-setting-store.ts
> mobile: fix tablet mode

- packages/editor/src/extensions/image/component.tsx
> Do not cache images without an hash i.e. pasted images

- apps/web/src/common/dialog-controller.tsx
- apps/web/src/dialogs/settings/auth-settings.ts
> Re-add missing change password logic

- apps/mobile/app/common/filesystem/upload.js
- apps/mobile/app/utils/note-bundle.js
- apps/mobile/share/editor.js
- apps/mobile/share/share.js
- apps/mobile/share/store.js
Attempt to possibly fix https://github.com/streetwriters/notesnook/issues/2785
> Fix saving note from share extension on mobile

- apps/mobile/app/package.json
- apps/mobile/package-lock.json
> mobile: fix topic sheet hidden on tablet after first open

- apps/web/src/common/dialog-controller.tsx
- apps/web/src/hooks/use-auto-updater.ts
> Do not show update available dialog on startup

- apps/mobile/app/navigation/navigation-stack.js
- apps/mobile/app/screens/notes/colored.tsx
- apps/mobile/app/screens/notes/monographs.tsx
- apps/mobile/app/screens/notes/tagged.tsx
- apps/mobile/app/screens/notes/topic-notes.tsx
- apps/mobile/app/services/navigation.ts
> mobile: navigation params can be undefined

- apps/mobile/app/components/sheets/manage-tags/index.js
> mobile: search tags with db.lookup

- apps/mobile/app/screens/trash/index.tsx
> mobile: fix trash cleanup interval text

- packages/editor/src/index.ts
> editor: fix cursor position on return

- apps/web/src/components/publish-view/index.jsx
> web: fix entering password closes publish dialog

- packages/editor/src/extensions/code-block/component.tsx
> editor: fix copy button is disabled in readonly mode

- apps/mobile/app/components/list/index.js
Closes https://github.com/streetwriters/notesnook/issues/2956
> mobile: fix sorting favorites

- apps/mobile/app/components/tabs/index.tsx
- apps/mobile/app/navigation/tabs-holder.js
- apps/mobile/app/services/device-detection.js
- apps/mobile/app/services/settings.ts
- apps/mobile/app/stores/use-setting-store.ts
> Fix tablet mode

- apps/web/src/common/export.ts
- apps/web/tsconfig.json
- packages/editor/src/extensions/text-direction/text-direction.ts
- packages/editor/src/index.ts
- packages/editor/src/utils/html.ts
- packages/editor/src/utils/tests/html.test.ts
This is a test.
\
\
\
\
\
\
And another world.
And this works!
> Replace <br> tags with paragraphs when pasting HTML

- docs/help/contents/importing-notes/import-notes-from-evernote.md
- docs/help/contents/importing-notes/import-notes-from-googlekeep.md
- docs/help/contents/importing-notes/import-notes-from-html-files.md
- docs/help/contents/importing-notes/import-notes-from-joplin.md
- docs/help/contents/importing-notes/import-notes-from-markdown-files.md
- docs/help/contents/importing-notes/import-notes-from-obsidian.md
- docs/help/contents/importing-notes/import-notes-from-onenote.md
- docs/help/contents/importing-notes/import-notes-from-plaintext-files.md
- docs/help/contents/importing-notes/import-notes-from-simplenote.md
- docs/help/contents/importing-notes/import-notes-from-standardnotes.md
- docs/help/contents/importing-notes/import-notes-from-zoho-notebook.md
> Make first step for importing notes clear as: go to importer.notesnook.com

- apps/web/vite.config.ts
Closes #2831
What needs to be tested:
> Fix "Dynamic module import is disabled" error on Firefox ESR & Tor Browser

- .github/workflows/web.beta.publish.yml
- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/components/editor/types.ts
> Prevent scroll jump when toggling focus mode

- apps/desktop/src/api/os-integration.ts
- apps/desktop/src/api/spell-checker.ts
- apps/desktop/src/api/updater.ts
- apps/desktop/src/main.ts
- apps/desktop/src/utils/config.ts
- apps/web/src/hooks/use-spell-checker.ts
- apps/web/src/stores/setting-store.js
This PR fixes privacy mode, automatic updates & spell checker settings in the desktop app.
> Fix desktop toggle settings

- apps/desktop/global.d.ts
- apps/desktop/package-lock.json
- apps/desktop/package.json
- apps/desktop/src/utils/protocol.ts
- apps/web/src/app-effects.tsx
- apps/web/src/interfaces/fs.ts
- packages/core/src/api/settings.js
- packages/core/src/api/sync/auto-sync.js
> Fix crash on uploading attachments

- apps/web/src/dialogs/settings/backup-export-settings.ts
> Allow encrypted backups for basic users

- apps/mobile/share/search.js
- Fix placeholder text incorrect when searching for notebook/tags
- Fix sorting of tags is messed up in Search
> Fix share sheet search sorting & placeholder

- apps/mobile/app/app.js
> Fix white flash on launch on ios

- packages/editor/src/extensions/clipboard-text-serializer/index.ts
- packages/editor/src/extensions/task-item/component.tsx
- packages/editor/src/extensions/task-list/component.tsx
- packages/editor/src/toolbar/components/counter.tsx
- packages/editor/src/toolbar/components/dropdown.tsx
- packages/editor/src/toolbar/components/split-button.tsx
- packages/editor/src/toolbar/components/tool-button.tsx
- Do not show background on hover
- Fix task item alignment on mobile
> Remove hover effect on mobile in editor

- apps/mobile/app/components/list/index.js
- packages/common/src/hooks/use-time-ago.ts
> mobile: fix list not updating on change date sort

- apps/mobile/app/services/sync.js
- apps/web/src/stores/app-store.js
This PR adds support for checking and running any pending sync in case sync was requested while another sync was running. This fixes the issue where the last few changes would not sync until either the sync was run manually or another change was made.
> Add support for running pending sync

- apps/mobile/app/common/filesystem/download.js
- apps/mobile/app/common/filesystem/upload.js
- apps/mobile/app/screens/editor/tiptap/use-editor.ts
> mobile: fix editor does not reset session id

- apps/mobile/app/common/filesystem/download-attachment.js
- apps/mobile/app/common/filesystem/download.js
- apps/mobile/app/common/filesystem/io.js
- apps/mobile/app/common/filesystem/upload.js
- apps/mobile/app/common/filesystem/utils.js
- apps/mobile/app/utils/note-bundle.js
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
> mobile: fix attachments fail to encrypt from share extension

- apps/mobile/app/components/selection-header/index.js
- apps/mobile/app/components/sheets/topic-sheet/index.tsx
> Fix/notebooks don't show tag/link to/export buttons

- apps/mobile/app/components/list-items/headers/section-header.js
- apps/mobile/app/components/list/index.js
- apps/mobile/app/hooks/use-group-options.ts
- apps/mobile/app/screens/home/index.tsx
- apps/mobile/e2e/tests/notebook.e2e.js
- apps/mobile/e2e/tests/sort.e2e.js
> mobile: fix sorting notes in topics

- apps/mobile/app/components/dialogs/result/pro-features.js
- apps/mobile/app/components/dialogs/vault/index.js
- apps/mobile/app/components/exception-handler/index.tsx
- apps/mobile/app/components/list-items/notebook/wrapper.js
- apps/mobile/app/components/note-history/preview.js
- apps/mobile/app/components/premium/compact-features.js
- apps/mobile/app/components/premium/features.js
- apps/mobile/app/components/sheets/github/issue.js
- apps/mobile/app/components/sheets/migrate/index.tsx
- apps/mobile/app/components/walkthroughs/walkthroughs.tsx
- apps/mobile/app/hooks/use-actions.js
- apps/mobile/app/hooks/use-app-events.js
- apps/mobile/app/screens/search/search-bar.js
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/screens/trash/index.tsx
- apps/mobile/app/services/premium.js
- apps/mobile/app/services/tip-manager.ts
- apps/mobile/native/ios/Notesnook.xcodeproj/project.pbxproj
- apps/mobile/native/worker.js
Found via `codespell -q 3 -S "*.patch"`
> mobile: fix typos in apps/mobile subdirectory

- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/components/styles.module.css
- packages/editor-mobile/src/components/title.tsx
- packages/editor-mobile/src/utils/index.ts
> mobile: support multi-line title

- apps/mobile/app/screens/editor/index.tsx
- apps/mobile/app/screens/editor/tiptap/commands.ts
- apps/mobile/app/screens/editor/tiptap/use-editor-events.ts
- apps/mobile/app/screens/editor/tiptap/use-editor.ts
Fix editor gets stuck sometimes when closing/reopening the same note over and over.
> mobile: fix session id mismatch causing editor to get stuck.

- apps/mobile/app/navigation/tabs-holder.js
Fix system bars colors incorrect when app is launched sometimes
> mobile: fix system bar colors

- apps/mobile/app/components/sheets/reminder/index.tsx
> Fix 24 hour reminder time in date picker

- packages/editor/src/index.ts
> Disallow links in inline code

- packages/core/src/api/index.js
- packages/core/src/api/token-manager.js
> Fix logout from all other devices

- apps/mobile/app/components/list-items/selection-wrapper/index.js
- apps/mobile/app/utils/functions.js
> mobile: fix selection state causing delete to fail

- apps/desktop/src/utils/autolaunch.ts
> Get rid of "Login Item Added" prompt on launch

- apps/web/src/dialogs/settings/other-settings.ts
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this project and the contribution
are public and …
> web: add link to source code in About Section in Setting

- apps/web/src/components/editor/header.tsx
> Show tags in readonly mode

- packages/editor/src/extensions/task-list/component.tsx
- packages/editor/src/extensions/task-list/task-list.ts
Closes #3797
Closes #3804
Closes #3801
> Fix task list title getting reset

- apps/mobile/app/components/premium/pricing-item.tsx
- apps/mobile/app/components/premium/pricing-plans.tsx
- apps/mobile/app/screens/settings/subscription.js
> mobile: fix crash on pricing plans page on ios

- apps/web/src/components/status-bar/index.tsx
Fixed the Email visibility Issue.
Have removed the {user.Email} and added Email not verified message besides the Dot.
> FIX:(#3770)Email visibility

- apps/mobile/app/common/database/logger.js
- apps/mobile/app/common/database/storage.js
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/web/src/interfaces/storage.ts
- packages/core/src/database/storage.js
- packages/core/src/logger.js
Closes #3847 
Closes #3479
Closes #3169
> Fix app freeze on startup due to intensive log deletion

- apps/mobile/app/components/auth/auth-modal.js
- apps/mobile/app/components/dialog/base-dialog.js
- apps/mobile/app/components/ui/sheet/index.js
> Fix app lock hides login page on enter background

- packages/editor/src/extensions/link/link.ts
> Handle md links with parentheses

- apps/web/src/dialogs/settings/components/importer.tsx
- apps/web/src/utils/importer.ts
This will allow users to import their notes even if a few of them throw errors.
> Make importer error resistant

- packages/editor/package-lock.json
- packages/editor/package.json
- packages/editor/src/extensions/link/link.ts
Closes #4005
Closes #4016 
Closes #4047 
Closes #4049 
Closes #4062 
Closes #4109 
Closes #4147
> Fix link pasting in editor

- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- packages/editor-mobile/src/components/editor.tsx
> Fix loading empty conent in editor on tablets

- apps/mobile/app/services/exporter.js
- apps/web/src/common/export.ts
- apps/web/src/components/note/index.tsx
- apps/web/src/utils/streams/export-stream.ts
- apps/web/src/utils/streams/utils.ts
- apps/web/src/utils/streams/zip-stream.ts
- packages/common/src/utils/file.ts
- packages/core/src/api/vault.js
- packages/core/src/collections/content.js
> web: added directory paths for exports

- apps/mobile/app/common/filesystem/download-attachment.js
- apps/mobile/app/components/attachments/actions.js
- apps/mobile/app/components/attachments/index.js
- apps/mobile/app/screens/editor/index.tsx
- apps/mobile/app/utils/note-bundle.js
> Fix attachments not loading when added from share extension

- .github/workflows/desktop.publish.yml
- apps/desktop/package-lock.json
- apps/desktop/package.json
- apps/desktop/sign.js
- apps/web/package-lock.json
- apps/web/package.json
> Code signed binaries for Windows

- apps/mobile/app/common/filesystem/compress.js
- apps/mobile/app/common/filesystem/io.js
- apps/mobile/app/components/dialogs/attach-image-dialog/index.tsx
- apps/mobile/app/components/ui/notice/index.tsx
- apps/mobile/app/screens/editor/tiptap/picker.js
- apps/mobile/app/utils/note-bundle.js
- apps/mobile/share/share.js
- apps/theme-builder/src/components/theme-builder/index.tsx
- apps/web/src/common/dialog-controller.tsx
- apps/web/src/components/editor/index.tsx
- apps/web/src/components/editor/picker.ts
- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/dialogs/image-picker-dialog.tsx
- apps/web/src/dialogs/index.ts
- apps/web/src/dialogs/settings/components/themes-selector.tsx
- apps/web/src/utils/file-picker.ts
- apps/web/src/utils/image-compressor.ts
Enable compression by default on all images while allowing users to optionally upload original images.
Closes #2749
Closes #2564
> Feat: image compression and mutli file upload

- apps/mobile/app/screens/editor/tiptap/types.ts
- apps/mobile/app/screens/editor/tiptap/use-editor-events.ts
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/stores/use-setting-store.ts
- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/dialogs/settings/editor-settings.ts
- apps/web/src/stores/setting-store.js
- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/utils/index.ts
> Add setting to toggle markdown shortcuts in the editor

- apps/mobile/app/services/backup.js
> mobile: fix crash during backup

- apps/mobile/app/components/list-items/note/wrapper.tsx
- apps/mobile/app/components/list-items/notebook/wrapper.tsx
- apps/mobile/app/components/list-items/reminder/index.tsx
- apps/mobile/app/components/list-items/selection-wrapper/index.tsx
- apps/mobile/app/components/list-items/tag/index.tsx
- apps/mobile/app/components/selection-header/index.tsx
> Disable multi-select actions if no items selected

- packages/editor/src/extensions/task-list/task-list.ts
> mobile: Fix position out of range error in editor

- packages/editor/styles/styles.css
> Fix placeholder showing always in first line of editor

- apps/mobile/app/components/side-menu/index.tsx
- apps/mobile/app/stores/use-menu-store.ts
> mobile: fix sidebar order not loading on app launch

- apps/mobile/app/components/tabs/index.tsx
- apps/mobile/app/navigation/tabs-holder.js
- apps/mobile/app/screens/editor/tiptap/use-editor-events.tsx
- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- apps/mobile/app/utils/events.js
> Fix back navigation from editor

- apps/mobile/app/components/selection-header/index.tsx
Selection header items have been moved to a dropdown menu
> Fix items in selection header are hidden on mobile screens

- apps/web/src/components/editor/index.tsx
- apps/web/src/components/editor/tiptap.tsx
- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/components/readonly-editor.tsx
- packages/editor/src/extensions/react/react-node-view.tsx
- packages/editor/src/extensions/react/react-portal-provider.tsx
- packages/editor/src/extensions/table/component.tsx
- packages/editor/src/index.ts
Closes #5008
Closes #4742 
Closes #4874 
Closes #4905 
Closes #4921 
Closes #4966 
Closes #4976 
Closes #4997
> Fix performance issues due to using portals for react node views

- apps/mobile/app/components/list-items/footer/index.js
- apps/mobile/app/components/list/index.tsx
Increase footer size for notebook screen to compensate for nested notebooks sheet.
> Fix footer size for notebook screen

- apps/mobile/native/package.json
- apps/mobile/package-lock.json
- apps/mobile/share/share.js
> Add support for setting note title form quick note widget

- apps/mobile/app/components/sheets/sort/index.js
> Fix cannot read property 'sortDirection' of undefined

- packages/editor/src/extensions/link/link.ts
> Fix n.startsWith is not a function

- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- apps/web/src/common/export.ts
- apps/web/src/components/editor/index.tsx
- apps/web/src/dialogs/progress-dialog.jsx
- apps/web/src/utils/streams/export-stream.ts
- packages/common/src/utils/export-notes.ts
This PR also fixes real time sync issues with locked notes.
> Fix locked notes not getting exported

- apps/mobile/app/components/sheets/sort/index.js
> mobile: fix cannot read property 'groupBy' of undefined

- apps/mobile/app/components/note-history/preview.js
- apps/mobile/app/screens/editor/readonly-editor.tsx
> Show diff in note history on mobile

- apps/mobile/app/common/database/encryption.js
- apps/mobile/app/components/app-lock-overlay/index.tsx
- apps/mobile/app/components/dialog/functions.ts
- apps/mobile/app/components/dialog/index.js
- apps/mobile/app/components/dialogs/applock-password/index.tsx
- apps/mobile/app/screens/settings/functions.js
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/services/settings.ts
- apps/mobile/app/stores/use-setting-store.ts
- Allow users to remove app lock with account password
- Allow users to disable privacy screen when app lock is enabled
- Fix issues with app lock giving error "Password incorrect" when unlocking the app sometimes
> Fix app lock on mobile

- apps/mobile/package-lock.json
- apps/mobile/share/share.js
1. Do not change title of note when choosing append to note
2. Fix color of title in widget
> Fix share widget title issues

- apps/mobile/app/services/message.js
> Fix recovery key dialog UI

- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/components/tiptap.tsx
- packages/editor-mobile/src/hooks/useEditorController.ts
> Recreate editor on changing note always

- apps/desktop/package-lock.json
- apps/desktop/package.json
- apps/desktop/src/api/sqlite-kysely.ts
- apps/desktop/src/main.ts
- apps/desktop/src/preload.ts
- apps/web/src/common/db.ts
- apps/web/src/common/sqlite/index.desktop.ts
- apps/web/src/common/sqlite/sqlite.worker.desktop.ts
- packages/core/__e2e__/__snapshots__/pricing.test.js.snap
- packages/core/__e2e__/sync.test.js
- packages/core/src/api/index.ts
- packages/core/src/logger.ts
- packages/core/vitest.config.ts
This will fix the lag during typing in desktop app.
> Run SQLite on another thread

- apps/mobile/app/components/app-lock-overlay/index.tsx
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/services/settings.ts
- apps/mobile/native/ios/Notesnook.xcodeproj/project.pbxproj
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/native/package.json
- apps/mobile/native/react-native.config.js
- apps/mobile/package-lock.json
- apps/mobile/patches/react-native-screenguard+1.0.0.patch
> mobile: fix privacy screen

- apps/mobile/app/components/sheets/github/issue.js
- apps/mobile/app/package.json
- apps/mobile/package-lock.json
Closes #6020
Closes #5788 
Closes #5842 
Closes #5843
Closes #5874 
Closes #5875
> mobile: fix cannot read property jsx of undefined

- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- apps/web/src/components/editor/index.tsx
> Fix real time editor sync not updating content

- packages/editor-mobile/src/components/tiptap.tsx
> mobile: fix error in editor with incorrect tools data

- packages/editor/src/extensions/search-replace/search-replace.ts
- packages/editor/src/toolbar/popups/search-replace.tsx
> Fix search/replace options not respected

- apps/web/src/components/editor/table-of-contents.tsx
- apps/web/src/components/editor/tiptap.tsx
> Fix note toc not loading on app restart

- packages/editor/src/hooks/use-editor.ts
> Fix editor options not applied

- apps/web/src/components/list-container/index.tsx
- apps/web/src/hooks/use-keyboard-list-navigation.ts
> Fix drag/drop with multiple items

- packages/editor/src/extensions/key-map/key-map.ts
> editor: fix keyboard shortcut for internal link not working

- apps/web/src/app-effects.mobile.ts
- apps/web/src/app.tsx
- apps/web/src/components/editor/action-bar.tsx
- apps/web/src/components/editor/index.tsx
- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/components/list-container/index.tsx
- apps/web/src/components/notice/index.tsx
- apps/web/src/hooks/use-slider.ts
- apps/web/src/stores/app-store.ts
- packages/editor/src/toolbar/toolbar.tsx
> Optimize ui for mobile & tablet form factor

- packages/editor-mobile/src/components/tiptap.tsx
- packages/editor/src/toolbar/tools/colors.tsx
> mobile: fix color popup not opening from main toolbar

- apps/web/src/components/editor/index.tsx
Closes #6080
Closes #6077
Closes #6067
Closes #6021
Closes #6046
Closes #5934
Closes #5990
> Fix editor scroll bar hiding sometimes on startup

- apps/mobile/app/components/app-lock-overlay/index.tsx
> mobile: fix keyboard blocks continue button on applock screen

- apps/mobile/app/services/settings.ts
> mobile: fix share sheet not loading on ios

- apps/mobile/app/services/backup.js
> mobile: fix backup share button not working

- apps/web/src/app-effects.tsx
- apps/web/src/dialogs/create-color-dialog.tsx
- apps/web/src/dialogs/item-dialog.tsx
- packages/core/src/collections/colors.ts
- packages/core/src/collections/notebooks.ts
- packages/core/src/collections/tags.ts
In v3, we temporarily removed limits on organization tools (tags, colors & notebooks). We are now bringing those limits back.
> Re-enable organization limits on basic plan

- apps/web/src/app.tsx
> web: Fix `isNarrow` overriding user-preference of navpane

- packages/editor/patches/prosemirror-view+1.33.1.patch
> Fix crash on drag dropping an embed node

- apps/mobile/app/hooks/use-app-events.tsx
- apps/mobile/app/services/background-sync.ts
- apps/mobile/app/services/sync.ts
- apps/web/src/stores/app-store.ts
- apps/web/src/utils/page-visibility.ts
- packages/core/src/api/index.ts
Currently, it takes several seconds for the sync to run after starting up the app. This PR fixes that to run the sync instantly as soon as the app loads.
> Improve sync on startup performance

- apps/mobile/app/screens/settings/settings-data.tsx
> Fix typo in Settings

- apps/desktop/src/api/updater.ts
- apps/web/src/components/status-bar/index.tsx
> Fix multiple updates running simultaneously

- packages/editor/styles/styles.css
> editor: fix heading and p gap

- packages/core/__tests__/lookup.test.js
- packages/core/src/api/lookup.ts
- packages/core/src/database/migrations.ts
- packages/core/src/utils/__tests__/query-transformer.test.ts
- packages/core/src/utils/query-transformer.ts
Fixes #6469
Fixes #6418
Fixes #6308
Fixes #6173
Fixes #6068
Fixes #5080
Fixes #5128
> Improve search query handling

- packages/core/__tests__/vault.test.js
- packages/core/src/api/vault.ts
> Fix locking notes with empty content

- apps/mobile/app/services/exporter.ts
> Do not zip note without attachments when exporting

- packages/editor/src/extensions/clipboard/clipboard-dom-parser.ts
- packages/editor/src/extensions/clipboard/clipboard-dom-serializer.ts
> editor: fix duplicate block-id when pasting content from note

- apps/web/src/dialogs/settings/components/importer.tsx
> Fix google-keep importer help link

- apps/mobile/app/services/exporter.ts
> Fix single file export on ios

- apps/web/src/dialogs/settings/index.tsx
> Fix right side panel of settings is not scrollable

- apps/mobile/app/common/filesystem/io.js
> mobile: fix cache dir does not exist error on bulkExist check

- apps/web/src/components/editor/action-bar.tsx
Signed-off-by: Zulfiqar Ali <85733202+01zulfi@users.noreply.github.com>
> web: fix note title not focusing until clicked twice (#6767)

- apps/web/src/common/vault.ts
- apps/web/src/components/status-bar/index.tsx
- apps/web/src/hooks/use-vault.ts
- packages/core/__tests__/vault.test.js
- packages/core/src/api/vault.ts
- packages/core/src/common.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
* add vault lock functionality for user
* add new vault EVENTS
Closes #6626
> web: add vault in status bar

- apps/mobile/app/components/auth/two-factor.js
- apps/mobile/app/components/auth/use-login.js
It's possible that user might have entered incorrect email address. The current version requires you to relaunch the app to enter new login details.
Closes [#6647](https://github.com/streetwriters/notesnook/issues/6647)
> Allow user to cancel 2fa auth on Mobile

- apps/mobile/app/components/list-items/notebook/wrapper.tsx
- apps/mobile/app/components/note-history/preview.js
- apps/mobile/app/components/selection-header/index.tsx
- apps/mobile/app/hooks/use-actions.tsx
- apps/mobile/app/utils/functions.js
- apps/web/src/components/trash-item/index.tsx
- apps/web/src/stores/trash-store.ts
- packages/core/src/collections/notebooks.ts
- packages/core/src/collections/trash.ts
- packages/core/src/common.ts
> web: fix restore notebooks over limit for free users (#6812)

- apps/web/src/components/editor/index.tsx
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
Signed-off-by: Zulfiqar Ali <85733202+01zulfi@users.noreply.github.com>
Closes #6822
> web: fix attachment preview logic (#6822)

- apps/web/src/components/editor/common.ts
- apps/web/src/components/editor/footer.tsx
- apps/web/src/components/editor/manager.ts
- apps/web/src/components/editor/tiptap.tsx
> web: add text zoom functionality in editor (#6633)

- apps/web/src/components/editor/footer.tsx
> web: fix button is not defined error

- apps/web/src/components/editor/action-bar.tsx
> web: fix close tab opening again

- apps/monograph/app/components/monographpost/clipboard.ts
- apps/monograph/app/components/monographpost/tiptap.tsx
fix monograph code block copied is invalid
> monograph: fix monograph code block copy

- apps/mobile/app/components/auth/two-factor.js
> mobile: fix error when changing 2fa method at login

- apps/mobile/app/components/dialogs/pdf-preview/index.js
- apps/mobile/app/screens/settings/attachment-group-progress.tsx
- apps/mobile/app/screens/settings/settings-data.tsx
> mobile: fix pdf-preview crash

- apps/mobile/app/components/list-items/reminder/index.tsx
- apps/mobile/app/components/list-items/selection-wrapper/index.tsx
- apps/mobile/app/components/sheets/relations-list/index.tsx
- apps/mobile/app/components/sheets/reminder/index.tsx
- apps/mobile/app/components/ui/reminder-time/index.tsx
1. Fix note headline not set automatically on creating reminder
2. Fix UI of reminder-time 
3. Fix UI of reminder in relations list
4. Fix relations-list does not update when relations change
Closes #6943
> mobile: fix reminder visual inconsistencies

- apps/web/src/dialogs/settings/backup-export-settings.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> web: always show desktop backup directory path (#6867)

- apps/monograph/app/components/monograph-chat.tsx
- apps/monograph/app/routes/_index.tsx
* use loader to get PUBLIC_URL
> monograph: fix PUBLIC_URL on client

- apps/monograph/app/components/monographpost/index.tsx
> monograph: remove callout headings from toc (#6875)

- apps/web/src/components/editor/tiptap.tsx
> web: round off zoom value

- packages/editor/src/extensions/inline-code/index.ts
- packages/editor/src/extensions/inline-code/inline-code.ts
- packages/editor/src/extensions/inline-code/tests/inline-code.test.ts
- packages/editor/src/index.ts
> editor: disable spellcheck for inline code

- extensions/web-clipper/README.md
> docs: add README.md for web clipper

- packages/core/src/utils/__tests__/internal-link.test.ts
- packages/core/src/utils/internal-link.ts
> core: handle error in parseInternalLink

- .commitlintrc.js
- extensions/web-clipper/src/content-scripts/all.ts
> webclipper: handle default case in listener

- apps/web/__e2e__/notes.test.ts
- apps/web/src/components/editor/index.tsx
- apps/web/src/stores/editor-store.ts
- packages/core/__tests__/notes.test.ts
- packages/core/src/collections/notes.ts
> web: fix tags editor not showing in locked note

- apps/web/src/dialogs/issue-dialog.tsx
- apps/web/src/utils/md.ts
> web: fix links in report issue dialog

- apps/web/src/common/vault.ts
> web: show account password label in delete vault dialog

- apps/web/src/components/editor/tiptap.tsx
- packages/editor/src/toolbar/toolbar.tsx
> Fix editor toolbar scroll styling

- apps/mobile/app/components/dialogs/vault/index.js
- apps/mobile/app/components/list-items/headers/section-header.tsx
- apps/mobile/app/components/selection-header/index.tsx
- apps/mobile/app/components/sheets/notebook-sheet/index.tsx
- apps/mobile/app/components/sheets/reminder/index.tsx
- apps/mobile/app/hooks/use-actions.tsx
- apps/mobile/app/package.json
- apps/mobile/app/screens/home/index.tsx
- apps/mobile/app/screens/notes/index.tsx
- apps/mobile/app/screens/settings/picker/pickers.jsx
- apps/mobile/app/utils/constants.ts
- apps/mobile/app/utils/functions.ts
- apps/mobile/package-lock.json
- apps/mobile/package.json
- apps/web/src/dialogs/add-reminder-dialog.tsx
- apps/web/src/dialogs/settings/components/billing-history.tsx
- apps/web/src/views/recovery.tsx
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/scripts/generate-strings.mjs
- packages/intl/src/strings.ts
Closes #7027
Closes #7002
Closes #7025
Closes #7014
> Fix localization

- apps/mobile/app/screens/settings/section-item.tsx
> mobile: Allow saving empty input in Settings

- packages/editor-mobile/src/components/editor.tsx
> mobile: fix undo/redo buttons in editor

- packages/core/src/api/lookup.ts
- packages/core/src/database/sql-collection.ts
- packages/core/src/utils/grouping.ts
search results are sorted by date created for now until we add proper support for sorting search results in the ui
> Add support for sorting search results

- packages/editor/src/extensions/task-list/component.tsx
- packages/editor/src/extensions/task-list/task-list.ts
* fix task list complete state not showing on first load
* fix task list allowing paste when readonly
Closes #7116 
Closes #6637
> editor: fix task list state & readonly bugs

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> intl: fix casing in legal & notebooks strings

- apps/web/src/components/status-bar/index.tsx
> web: fix status bar size changing

- packages/editor/src/extensions/check-list/check-list.ts
- packages/editor/src/extensions/task-list/task-list.ts
> editor: handle input for checklist

- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/hooks/useEditorController.ts
> mobile: fix scroll jumping in realtime sync

- apps/mobile/app/screens/editor/tiptap/picker.ts
- apps/mobile/app/utils/note-bundle.js
- apps/mobile/native/ios/Podfile.lock
- apps/mobile/package-lock.json
- packages/editor-mobile/package-lock.json
- packages/editor/src/extensions/check-list/check-list.ts
Closes #7196
Closes #7199
Closes #7245
Closes #7188
> Fix image file upload

- apps/mobile/app/screens/settings/picker/pickers.jsx
> mobile: fix trash interval picker text showing NaN

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> intl: fix referencedIn casing

- apps/web/__e2e__/app-lock.test.ts
- apps/web/__e2e__/models/app.model.ts
- apps/web/__e2e__/models/settings-view.model.ts
- apps/web/__e2e__/models/utils.ts
- apps/web/__e2e__/utils/index.ts
- apps/web/src/components/status-bar/index.tsx
> web: add lock app button in status bar

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> intl: fix follow casing

- apps/mobile/patches/react-native-material-menu+2.0.0.patch
Fix material menu shows up again after being closed.
Closes #7328
Closes #7267
> mobile: fix material menu

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> global: fix search strings

- apps/web/src/app.css
- apps/web/src/components/list-container/index.tsx
- apps/web/src/stores/editor-store.ts
> web: fix reveal in list

- packages/editor-mobile/src/index.tsx
> mobile: fix strings not rendering correctly in editor

- packages/editor/src/extensions/search-replace/search-replace.ts
> editor: fix search not resetting when closed

- apps/mobile/app/services/backup.ts
> mobile: close sheet on backup completed

- apps/mobile/app/screens/editor/tiptap/picker.ts
> mobile: fix attaching a file in new note editor

- apps/mobile/app/hooks/use-app-events.tsx
- apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/NotePreviewWidget.java
- apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/ReminderViewsService.java
- apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/ReminderWidgetProvider.java
- apps/mobile/native/android/app/src/main/res/values/colors.xml
> mobile: fix android widget bugs

- packages/editor/src/toolbar/popups/color-picker.tsx
- packages/editor/src/toolbar/tools/colors.tsx
> editor: fix hover styling in toolbar color buttons

- apps/mobile/app/components/sheets/update/index.js
> mobile: fix release notes rendering

- apps/web/src/views/notebook.tsx
This solves the issue mentioned here: #7110
> editor: fix subnotebook title

- apps/mobile/app/common/filesystem/utils.ts
> mobile: fix file size is 0 errors when downloading attachments

- apps/web/src/stores/user-store.ts
- apps/web/src/utils/config.ts
> web: keep some configs in local storage on logout

- apps/mobile/app/services/settings.ts
Closes #7414
@01zulfi kindly fix this on web/desktop too
> Restore device specific settings on logout

- apps/web/src/components/route-container/index.tsx
- packages/core/src/utils/query-transformer.ts
Fixes: #7411
Special characters were not escaped properly
> web: fix search special characters

- apps/web/__e2e__/editor.test.ts
- apps/web/__e2e__/models/editor.model.ts
- apps/web/src/components/editor/action-bar.tsx
> web: hide undo & redo buttons for readonly notes

- apps/mobile/app/screens/editor/tiptap/use-editor.ts
- apps/web/__e2e__/models/tab-item.model.ts
- apps/web/__e2e__/tabs.test.ts
- apps/web/src/components/editor/action-bar.tsx
- apps/web/src/stores/editor-store.ts
> Disable all kinds of navigation in pinned tabs

- packages/editor/styles/styles.css
> editor: improve hr & p styling

- packages/editor/src/index.ts
> editor: add scroll margin & threshold props

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> intl: fix account casing

- apps/web/__e2e__/models/editor.model.ts
- apps/web/__e2e__/tabs.test.ts
- apps/web/src/components/editor/header.tsx
- apps/web/src/stores/editor-store.ts
> web: fix tags not adding/removing in note header bar

- apps/web/__e2e__/tabs.test.ts
- apps/web/src/stores/editor-store.ts
> web: fix note title sync if note is opened in multiple tabs

- apps/web/src/dialogs/attachments-dialog.tsx
* assign min-height to container
> web: fix attachment table height for few items

- apps/web/src/components/editor/tiptap.tsx
- packages/editor/src/extensions/link/helpers/clickHandler.ts
- packages/editor/src/index.ts
> editor: open internal links in new tab for middle mouse click

- packages/editor/src/toolbar/floating-menus/hover-popup/index.tsx
> editor: hide hover popup if right click occurs before popup is shown

- apps/web/src/common/key-map.ts
- apps/web/src/dialogs/settings/index.tsx
> web: open settings kbd shortcut && autofocus settings search field

- apps/web/src/components/editor/title-box.tsx
> web: align note title with rest of ui

- apps/web/__e2e__/models/notebook-item.model.ts
- apps/web/__e2e__/notebooks.test.ts
- apps/web/src/stores/editor-store.ts
* when default notebook is set, adding notes in tag and color context should also add that note to default notebook
Closes #7696
> web: update default notebook behavior

- packages/core/src/utils/fuzzy.ts
- packages/editor/src/extensions/task-item/component.tsx
- packages/editor/styles/styles.css
> editor: fix task item padding

- apps/web/src/components/editor/header.tsx
The PR fixes UI flicker when creating a new note on web app.
> web: fix ui flicker in editor when creating new note

- apps/web/src/components/notebook-header.tsx
> web: restore notebook crumbs

- apps/web/src/components/editor/table-of-contents.tsx
- packages/editor/src/utils/toc.ts
> editor: fix scroll into view when used by toc

- apps/web/src/components/editor/index.tsx
- apps/web/src/stores/editor-store.ts
> web: fix editor rerendering on session type change from new to default

- apps/web/src/dialogs/add-reminder-dialog.tsx
> web: increase reminder dialog width

- apps/web/src/components/navigation-menu/index.tsx
> web: collapse hovered navbar when item is clicked

- apps/web/src/views/auth.tsx
> web: mask email in session expired page description

- apps/web/src/components/editor/footer.tsx
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> web: add reset zoom button

- apps/web/src/components/editor/footer.tsx
- apps/web/src/dialogs/command-palette/commands.ts
- apps/web/src/stores/app-store.ts
- apps/web/src/utils/fullscreen.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> web: add toggle focus mode command

- packages/editor/src/extensions/clipboard/clipboard-text-parser.ts
Closes https://github.com/streetwriters/notesnook/issues/7799
Closes #7801
> Editor: do not use look behind regex

- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/dialogs/settings/editor-settings.ts
- apps/web/src/stores/setting-store.ts
- packages/editor/src/extensions/font-ligature/font-ligature.ts
- packages/editor/src/extensions/font-ligature/index.ts
- packages/editor/src/index.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> editor: font ligatures for common symbols

- apps/web/__e2e__/search.test.ts
- apps/web/src/components/route-container/index.tsx
> web: show create btn when searching && clear search when closed via btn

- apps/web/src/components/note/index.tsx
> web: add publish:update item in note menu options

- apps/web/src/views/all-notes.tsx
> web: fix search result note item not updating

- apps/web/src/dialogs/command-palette/command-palette-dialog.tsx
* Remove overflow: hidden styling from GroupedVirtuoso
Closes #7845
> web: fix command palette not scrolling

- apps/web/src/common/key-map.ts
- apps/web/src/stores/editor-store.ts
> web: don't close pinned tab on ctrl+w

- packages/editor/src/extensions/link/link.ts
> editor: disable spellcheck for links

- apps/web/__e2e__/tabs.test.ts
- apps/web/src/stores/editor-store.ts
* don't close tab if note was present in tab history
Closes #7679
> web: fix close tab on trashing note

- apps/web/src/components/diff-viewer/index.tsx
- apps/web/src/components/editor/action-bar.tsx
- apps/web/src/components/properties/index.tsx
* add close button to quit diff viewer
* allow property pane to open with only note history list
> web: improve diff viewing

- apps/web/src/components/notice/index.tsx
> web: wrap notice text

- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> intl: fix notes string

- apps/web/src/components/virtualized-tree/index.tsx
- apps/web/src/dialogs/move-note-dialog.tsx
- apps/web/src/views/notebooks.tsx
* fix flicker when creating a new notebook/subnotebook
* fix crash when creating subnotebook
* fix notebook not expanding when subnotebook is created against it
> web: fix notebooks tree

- apps/web/src/components/editor/table-of-contents.tsx
- packages/editor/src/utils/toc.ts
* fix duplicate headings showing in toc view
* fix negative level for some headings
> web: fix toc bugs

- apps/web/src/components/field/index.tsx
- apps/web/src/components/route-container/index.tsx
> web: show reset search button only when query text present

- apps/web/src/app.css
- apps/web/src/components/navigation-menu/index.tsx
This part should be draggable now
> web: make part of nav menu header draggable

- packages/editor-mobile/public/index.html
> mobile: fix default font setting not followed

- apps/web/__e2e__/models/app.model.ts
- apps/web/__e2e__/models/note-properties.model.ts
- apps/web/__e2e__/notes.test.ts
- apps/web/src/components/icons/index.tsx
- apps/web/src/components/list-container/types.ts
- apps/web/src/components/navigation-menu/index.tsx
- apps/web/src/components/note/index.tsx
- apps/web/src/components/properties/index.tsx
- apps/web/src/hooks/use-tip.ts
- apps/web/src/navigation/routes.tsx
- apps/web/src/stores/editor-store.ts
- apps/web/src/stores/note-store.ts
- apps/web/src/views/notes.tsx
- packages/core/__tests__/notes.test.ts
- packages/core/src/collections/notes.ts
- packages/core/src/collections/relations.ts
- packages/core/src/collections/settings.ts
- packages/core/src/database/index.ts
- packages/core/src/database/migrations.ts
- packages/core/src/types.ts
- packages/core/src/utils/array.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
Closes https://github.com/streetwriters/notesnook/issues/7796
Related https://github.com/streetwriters/notesnook/pull/2654
Closes https://github.com/streetwriters/notesnook/issues/228
> web: archive notes

- apps/web/src/navigation/routes.tsx
> web: fix notestore is not defined error

- apps/mobile/app/screens/editor/tiptap/use-editor.ts
> mobile: fix typing in editor title input

- apps/mobile/app/components/sheets/sort/index.tsx
- apps/mobile/app/hooks/use-group-options.ts
> mobile: fix crash in list

- packages/core/__tests__/notes.test.ts
- packages/core/src/collections/notes.ts
- packages/core/src/content-types/tiptap.ts
- packages/core/src/utils/html-parser.ts
> core: segregate logic for note headline and note headline title generation

- packages/editor/src/toolbar/floating-menus/hover-popup/index.tsx
* move it down so it doesn't block the link
Related https://github.com/streetwriters/notesnook/issues/7978
> editor: improve hover link popup position

- apps/web/src/app.tsx
- apps/web/src/components/split-pane/index.tsx
* fix list pane not expanding to saved width on reload
* fix list pane not expanding to saved width on collapse
> web: fix list pane not expanding

- apps/web/src/common/notices.ts
> web: fix automatic backup reminder setting reverting to never

- apps/web/src/app.css
Closes https://github.com/streetwriters/notesnook/issues/8024
> web: assign accent color to links

- apps/web/__e2e__/models/app.model.ts
- apps/web/__e2e__/notes.test.ts
> web: add more archive test cases

- packages/core/__tests__/settings.test.js
- packages/core/src/collections/settings.ts
> core: fix trash cleanup interval setting retrieval

- apps/mobile/app/hooks/use-app-events.tsx
- apps/mobile/app/screens/settings/settings-data.tsx
- apps/mobile/app/stores/use-setting-store.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
Add option in Settings -> Behavior to disable auto update check on mobile.
Closes #8089
> mobile: add option to disable auto update check

- packages/editor/styles/styles.css
> editor: fix alignment items in callout heading

- apps/web/src/dialogs/command-palette/command-palette-dialog.tsx
https://github.com/user-attachments/assets/354efe65-4f4f-40fe-be68-116e13af8808
> web: press shift+enter to create note in quick open

- apps/web/src/dialogs/command-palette/command-palette-dialog.tsx
> web: del kbd btn support for removing recents in command palette

- packages/core/src/collections/settings.ts
Related https://github.com/streetwriters/notesnook/pull/8045
> core: fix db.settings.getTrashCleanupInterval return type

- apps/web/src/components/editor/action-bar.tsx
- apps/web/src/stores/editor-store.ts
> web: add dragndrop support for notes on tab strip

- apps/web/src/utils/config.ts
Closes https://github.com/streetwriters/notesnook/issues/8088
> web: persist double spaced lines config on logout

- apps/mobile/app/screens/settings/settings-data.tsx
> mobile: fix crash in settings -> user subscription

- apps/mobile/share/share.js
> mobile: add line break when appending to note

- apps/mobile/app/components/sheets/reminder/index.tsx
- apps/mobile/app/hooks/use-actions.tsx
> mobile: fix new reminder title/headline is not autofill

- apps/web/__e2e__/models/notebook-item.model.ts
- apps/web/__e2e__/notebooks.test.ts
- apps/web/src/components/icons/index.tsx
- apps/web/src/components/notebook/index.tsx
- apps/web/src/dialogs/command-palette/commands.ts
- packages/core/__tests__/notebooks.test.js
- packages/core/src/collections/notebooks.ts
> web: add 'move to top' for sub-notebooks

- packages/editor/src/extensions/link/helpers/clickHandler.ts
> editor: support ctrl/cmd+click to open internal links in new tab

- packages/editor/styles/styles.css
> editor: remove styling for sibling elements of double spaced paragraphs

- apps/web/__e2e__/models/item.model.ts
- apps/web/__e2e__/tags.test.ts
- apps/web/src/components/tag/index.tsx
- apps/web/src/stores/editor-store.ts
- packages/core/src/collections/settings.ts
- packages/core/src/types.ts
> web: default tags

- apps/web/src/components/navigation-menu/index.tsx
- apps/web/src/dialogs/command-palette/commands.ts
- apps/web/src/stores/app-store.ts
> web: fix navigation commands in command palette

- apps/web/src/components/note/index.tsx
> web: fix navigating to notebooks & tags from note item

- apps/mobile/app/screens/search/index.tsx
- apps/web/src/views/all-notes.tsx
- apps/web/src/views/notes.tsx
- packages/core/src/api/lookup.ts
> web: fix archived notes showing in search results

- packages/editor/src/toolbar/tools/inline.tsx
Closes https://github.com/streetwriters/notesnook/issues/8223
> editor: don't clear nodes in clear formatting option

- apps/web/src/components/status-bar/index.tsx
> web: fix update status height

- apps/web/src/components/search-result/index.tsx
> web: support compact search results view

- apps/web/src/dialogs/settings/backup-export-settings.ts
- packages/common/src/utils/export-notes.ts
- packages/core/src/collections/notes.ts
- packages/core/src/utils/templates/md.ts
> common: include archive in export

- apps/web/src/components/editor/index.tsx
- apps/web/src/components/search-result/index.tsx
- apps/web/src/stores/editor-store.ts
- packages/core/src/api/lookup.ts
- packages/core/src/types.ts
- packages/core/src/utils/html-parser.ts
- packages/editor/src/extensions/search-result/search-result.ts
> web: fix scroll to search result

- apps/web/__e2e__/models/tab-item.model.ts
- apps/web/__e2e__/tabs.test.ts
- apps/web/src/components/editor/action-bar.tsx
> web: disable reveal in list option when focus mode active

- apps/web/src/components/editor/footer.tsx
- apps/web/src/components/editor/manager.ts
- apps/web/src/components/editor/tiptap.tsx
- apps/web/src/components/editor/types.ts
- packages/editor/src/index.ts
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> web: add character, spaces, paragraphs count in status bar popup

- apps/mobile/app/services/background-sync.ts
- apps/mobile/native/android/app/src/main/AndroidManifest.xml
- apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/BootTaskService.java
Switch to using `specialUse` permission to run foreground service on device boot from `BOOT_COMPLETED` broadcast on android.
> Fix boot crash on android

- apps/monograph/app/components/monographpost/index.tsx
- apps/monograph/app/routes/$id.tsx
> monograph: fix API_HOST on client

- apps/web/src/dialogs/settings/components/customize-toolbar.tsx
> web: fix toolbar crash

- apps/web/src/components/importer/components/provider-selector.tsx
> web: fix github link in importer setting

- apps/mobile/app/components/selection-header/index.tsx
- apps/mobile/app/components/side-menu/index.tsx
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
> Fix crash on moving notebook when no notebooks selected

- apps/mobile/app/components/ui/sheet/index.js
- apps/mobile/app/navigation/fluid-panels-view.tsx
- apps/mobile/app/screens/editor/wrapper.tsx
- apps/mobile/app/stores/use-theme-store.ts
- apps/mobile/app/utils/notesnook-module.ts
- apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java
- apps/mobile/patches/react-native-actions-sheet+0.9.7.patch
Closes #8341
Closes #8340
Closes https://github.com/streetwriters/notesnook/issues/8228
> mobile: fix nav bar handling on android 15 and above

- apps/mobile/app/components/properties/color-tags.tsx
> mobile: fix crash on long press color tag

- apps/mobile/app/stores/index.ts
> mobile: Fix sidebar items do not update after sync

- packages/common/src/utils/export-notes.ts
* fix "_archive" folder generation for each archive note
> common: fix archive export

- apps/web/src/app.tsx
- apps/web/src/components/route-container/index.tsx
> web: fix nav pane on small screens

- apps/web/src/dialogs/note-linking-dialog.tsx
> web: migrate note linking dialog lists from tanstack virtual to virtuoso

- apps/mobile/app/components/fluid-panels/index.tsx
- apps/mobile/app/navigation/fluid-panels-view.tsx
- packages/editor-mobile/src/components/editor.tsx
- packages/editor-mobile/src/components/header.tsx
- packages/intl/locale/en.po
- packages/intl/locale/pseudo-LOCALE.po
- packages/intl/src/strings.ts
1. Fix tapping on bottom area to focus and open the keyboard
2. Added scroll to top and scroll to bottom buttons in drop down menu
3. Fix keyboard does not open when swiping to open editor on a blank note
> Mobile editor ux improvement

- packages/editor/src/extensions/link/link.ts
- packages/editor/src/extensions/link/tests/__snapshots__/link.test.ts.snap
- packages/editor/src/extensions/link/tests/link.test.ts
Fixes https://github.com/streetwriters/notesnook/issues/8180
Not deeply familiar with all the url formats, let me know if something that needs to be tested.
Tested html urls, markdowns, and something like http://example.com
cc @01zulfi
> Handle pasting urls in html

- apps/web/src/common/key-map.ts
> web: fix open settings shortcut interfering with editor shortcut

- docs/help/contents/keyboard-shortcuts.md
- packages/common/src/utils/keybindings.ts
> common: update keybindings for editor search, link, internal link, and command palette

- apps/web/src/app.tsx
> web: increase list pane max size to 1000 for large screens

- apps/mobile/app/components/side-menu/side-menu-notebooks.tsx
- apps/mobile/app/components/side-menu/side-menu-tags.tsx
> Fix filtered tags and notebooks not sorted correctly

- packages/core/src/api/sync/index.ts
https://github.com/streetwriters/notesnook-sync-server/pull/43
> web: use RequestFetchV2 hub method

- apps/web/src/views/reminders.tsx
> web: fix deleting a reminder not removing from search list

- packages/editor/package-lock.json
- packages/editor/package.json
- packages/editor/src/extensions/table/actions.ts
- packages/editor/src/extensions/table/component.tsx
- packages/editor/src/index.ts
- packages/editor/src/toolbar/tools/table.tsx
- packages/editor/styles/styles.css
> editor: improve table styling

- packages/editor/src/components/resizer/index.tsx
- packages/editor/src/extensions/image/component.tsx
https://github.com/user-attachments/assets/a514d46e-0d4c-40a8-bec7-c33db4074aea
> editor: show image dimensions during drag resizing

- apps/mobile/app/components/side-menu/notebook-item.tsx
- apps/mobile/app/components/side-menu/side-menu-notebooks.tsx
- apps/mobile/app/screens/link-notebooks/index.tsx
- apps/mobile/app/screens/move-notebook/index.tsx
- apps/mobile/app/stores/create-notebook-tree-stores.ts
Remove duplicate Notebooks when searching for in the Notebook Tree
> Fix Notebook Tree when Searching for Notebooks

- apps/web/src/common/dialog-manager.tsx
> web: fix settings not opening again after navigation from attachment manager

- apps/web/src/dialogs/mfa/steps.tsx
> web: enforce sms2FA feature limit

- apps/web/src/common/db.ts
- apps/web/src/components/error-boundary/index.tsx
- apps/web/src/utils/logger.ts
i thought service workers would work on Android but unfortunately, they are super flaky causing lots of issues. I might revisit it later.
> Fix web app not working on mobile devices

- packages/core/__tests__/tags.test.ts
- packages/core/src/database/sql-collection.ts
Closes https://github.com/streetwriters/notesnook/issues/8610
> core: fix tag sort by title

- packages/core/src/content-types/__tests__/__snapshots__/tiptap.test.js.snap
- packages/core/src/content-types/__tests__/tiptap.test.js
- packages/core/src/content-types/tiptap.ts
- packages/core/src/utils/templates/text.ts
Closes https://github.com/streetwriters/notesnook/issues/8582
> core: fix leading spaces in txt export && remove unneeded space at start of txt

- packages/editor/src/extensions/math/math-block.ts
- packages/editor/src/extensions/math/math-inline.ts
> editor: support pasting math

- docs/help/contents/importing-notes/import-notes-from-standardnotes.md
https://github.com/streetwriters/notesnook-importer/pull/229
> docs: add standard notes import instructions

- apps/web/src/common/notices.ts
> web: don't show auto-backup notice again after dismissal

- apps/mobile/e2e/tests/auth.e2e.ts
- apps/mobile/e2e/tests/note.e2e.ts
- apps/mobile/e2e/tests/notebook.e2e.ts
- apps/mobile/e2e/tests/search.e2e.ts
- apps/mobile/e2e/tests/sort.e2e.ts
- apps/mobile/e2e/tests/tag.e2e.ts
- apps/mobile/e2e/tests/utils.ts
- apps/mobile/e2e/tests/vault.e2e.ts
Uses a builder pattern for writing tests to reduce code and simplify writing tests
> mobile: refactor e2e tests

- packages/common/src/utils/keybindings.ts
- packages/editor/src/toolbar/tools/headings.tsx
Closes https://github.com/streetwriters/notesnook/issues/8732
> common: fix insert paragraph keybinding
