apps/mobile/app/components/list-items/headers/notebook-header.js, apps/mobile/app/components/list-items/selection-wrapper/action-strip.js, apps/mobile/app/components/side-menu/pinned-section.js, apps/mobile/app/hooks/use-actions.js, apps/mobile/app/stores/use-menu-store.ts, apps/web/src/components/navigation-menu/index.js, apps/web/src/components/notebook/index.js, apps/web/src/components/tag/index.js, apps/web/src/components/topic/index.js, apps/web/src/stores/app-store.js, apps/web/src/views/topics.js, packages/core/__tests__/settings.test.js, packages/core/__tests__/shortcuts.test.js, packages/core/api/index.js, packages/core/api/migrations.js, packages/core/api/settings.js, packages/core/api/sync/collector.js, packages/core/api/sync/merger.js, packages/core/collections/notebooks.js, packages/core/collections/shortcuts.js, packages/core/collections/tags.js, packages/core/collections/topics.js, packages/core/database/backup.js, packages/core/database/cached-collection.js, packages/core/migrations.js
This is a **BREAKING** change. We are moving `pins` out of `settings` as they really don't belong there (not to mention the confusing name). Shortcuts (formerly `pins`) will have their own collection which will be synced like `notes`, `notebooks` etc.
1. `db.settings.pins` -> `db.shortcuts.resolved`
2. `db.settings.isPinned` -> `db.shortcuts.exists`
3. `db.settings.pin` -> `db.shortcuts.add`
4. `db.settings.unpin` -> `db.shortcuts.remove`
This will fix various issues where shortcuts would randomly go missing.
Fixes #534
Fixes #536
@ammarahm-ed this will require changes in the client code.
=> Add separate collection for shortcuts

packages/core/api/sync/merger.js, packages/core/collections/shortcuts.js, packages/core/common.js, packages/core/database/cached-collection.js, packages/core/database/indexer.js, packages/core/database/migrator.js, packages/core/database/storage.js, packages/core/migrations.js
This needs to be quite heavily tested especially the syncing. We also might have to move the database version ahead to stop potential issues on older versions.
=> Fix issue where a single item could have duplicate shortcuts

packages/editor/src/extensions/key-map/index.ts, packages/editor/src/extensions/key-map/key-map.ts, packages/editor/src/index.ts
Pressing `Tab` inside the editor will now add the `\t` character at the selection position.
=> Allow tabbing inside editor

packages/editor/src/extensions/react/react-node-view.tsx, packages/editor/src/extensions/task-list/task-list.ts
This overrides the default task item drop behavior to make dropping items at the very end of the task list more reliable. Currently, dropping the item at the end of the list creates a new list which is often not what you want. We look for such behavior and instead moves the item to the very end.
Fixes #1127
=> Don't create a new task list when dropping items at end

apps/mobile/app/components/sheets/sort/index.js, apps/mobile/app/utils/constants.js
Removed sort option 'dateEdited' from tags screen & replaced it with 'dateModified'.
=> mobile: remove dateEdited from sort options in Tags

packages/core/content-types/__tests__/__snapshots__/tiptap.test.js.snap, packages/core/content-types/__tests__/tiptap.test.js, packages/core/content-types/tiptap.js, packages/core/package-lock.json, packages/core/package.json
This PR adds support for a more structured output when converting from HTML to text using `html-to-text` library which preserves a lot of the formatting like tables, lists, task lists etc.
=> Improve HTML to text conversion for exporting

apps/mobile/app/components/launcher/index.js
Hide the biometrics unavailable error on mobile if fingerprint/face id is not registered.
=> mobile: hide biometrics unavailable toast

apps/web/src/interfaces/fs.js, packages/core/collections/attachments.js, packages/core/collections/content.js, packages/core/content-types/tiptap.js, packages/core/database/fs.js
This fixes a critical issue where images appeared broken after switching notes.
Closes #1536
Closes #1453
Closes #1197
Closes #1195
=> Add support for caching base64 images

apps/web/desktop/events.js, apps/web/desktop/ipc/actions/bringToFront.js, apps/web/desktop/ipc/actions/index.js, apps/web/desktop/ipc/actions/showNotification.js, apps/web/src/commands/bring-to-front.js, apps/web/src/commands/show-notification.js, apps/web/src/stores/reminder-store.js
This gives us access to APIs such as `urgency` & `timeoutType` which map well to reminder priorities.
=> Use native electron notifications in desktop app

packages/editor/src/extensions/code-block/highlighter.ts, packages/editor/src/extensions/list-item/commands.ts
Closes #1770
This was caused by not deleting old syntax highlighting decorations before applying new ones. The result was a huge amount of extra decorations on the same nodes causing huge performance issues, not to mention other bugs.
=> Fix issue where changes in code block were not properly highlighted

apps/web/src/app-effects.js, apps/web/src/common/dialog-controller.tsx, apps/web/src/components/announcements/body.js, apps/web/src/components/announcements/index.js, apps/web/src/components/dialogs/announcement-dialog.js, apps/web/src/components/list-container/index.tsx, apps/web/src/stores/announcement-store.js, apps/web/src/stores/app-store.js
Previously, we were fetching the announcements multiple times on app startup. This was unnecessary. This PR moves announcements to their own zustand store which gives global access to the whole app.
Next steps would include regular fetching or using SSE.
=> Fetch announcements only once on app startup

packages/editor-mobile/src/components/tags.tsx, packages/editor-mobile/src/components/title.tsx
On some mobile screens, tags appear to have no background color, therefore I have added borders to distinguish them properly. 
- Fixed clicking on tag to delete
- Added scrolling when tags are greater than screen width.
=> Add borders/scrolling to tagbar on mobile

packages/editor-mobile/src/components/editor.tsx, packages/editor/src/extensions/keep-in-view/keep-in-view.ts
In the last update, scroll into view broke on ios devices after updating ProseMirror. This fixes it.
=> mobile: fix scroll into view on ios

apps/mobile/app/common/filesystem/download-attachment.js, apps/mobile/app/components/image-preview/index.js, apps/mobile/app/screens/editor/source.ts, apps/mobile/app/screens/editor/tiptap/editor-events.ts, apps/mobile/app/screens/editor/tiptap/use-editor-events.ts, packages/editor-mobile/src/components/editor.tsx, packages/editor-mobile/src/hooks/useEditorController.ts, packages/editor-mobile/src/utils/index.ts, packages/editor/src/extensions/attachment/attachment.ts, packages/editor/src/index.ts, packages/editor/src/toolbar/icons.ts, packages/editor/src/toolbar/tool-definitions.ts, packages/editor/src/toolbar/tools/attachment.tsx, packages/editor/src/toolbar/tools/index.ts
This adds support for basic attachment preview support. Currently only image previews are supported on mobile.
- Fixed image downloading not working on mobile
- Added image preview support on mobile with support for loading full quality images in full screen.
- Added Attachment preview logic in editor, so in future we can support preview for other files such as audio & video
=> feat: image preview & download

packages/core/api/healthcheck.js, packages/core/api/user-manager.js
This closes #1362.
Previously, we were force logging out users anytime we got a `401 unauthorized` error. This was finicky and caused a lot of frustration to users. This PR adds a health check to the auth server (in case the auth server is down) + a few other checks to make sure that when we do log out the user, it is under correct circumstances.
=> Do a healthcheck before logging out user on session revoke

apps/web/src/views/settings.js, packages/core/api/index.js, packages/core/api/subscriptions.js
This was a long standing bug where a user was required to reach out to us via email to get their subscription cancelled. This was highly cumbersome & user unfriendly behavior.
This PR fixes this by making subscription cancellation a one click process.
=> Simplify subscription cancellation

apps/mobile/app/navigation/tabs-holder.js, apps/mobile/patches/react-native+0.69.7.patch
- Fix orientation change from portrait to landscape makes the editor smaller than screen size.
- Fix orientation change in fullscreen mode from portrait to landscape resizes the editor to take a small part of screen
Fixes #2120
=> mobile: fix ipad orientation window sizing

apps/mobile/app/package.json, apps/mobile/app/screens/editor/loading.js, apps/mobile/app/screens/editor/tiptap/use-editor.ts, apps/mobile/native/package.json, apps/mobile/package.json, packages/editor-mobile/src/components/editor.tsx, packages/editor-mobile/src/components/statusbar.tsx, packages/editor-mobile/src/hooks/useEditorController.ts, packages/editor-mobile/src/utils/index.ts
1. Previously if a note had smaller content, loading would still take quite a bit long which seemed unnecessary. Now loading will show only if note takes long enough to load which should make the app feel much more snappier than before when opening notes. The editor also assumes that notes with less characters in content will load quickly meaning no loading screen for notes at all which are count less than 50K characters. This seems to be a fair limit I think.
2.  Previously when opening note, the word count on mobile would be 0, then update to actual word count. This has been fixed so correct word count shows when opening note without any delay.
3. When changing a note, editor will scroll to top automatically now.
4. I noticed a race condition in the editor causing the content to be …
=> Mobile editor improvements

packages/core/api/sync/collector.js, packages/core/collections/notes.js
Deleted notes in core must specify if they were deleted after being marked as local only. Otherwise there's a chance that offline note might get deleted on force sync from other devices. Closes #2291
=> core: fix notes marked as local only get deleted on sync

apps/web/src/common/dialog-controller.tsx, packages/core/collections/tags.js
=> core: disable color-name-sanitization

packages/editor/src/toolbar/tools/link.tsx, packages/editor/src/toolbar/tools/web-clip.tsx, packages/editor/src/utils/prosemirror.ts
=> Fix crash while editing links on mobile

apps/mobile/app/components/sheets/reminder/index.tsx
As reported in #2330 when selecting repeat mode, current date's day should be selected automatically.
=> mobile: auto select current day when repeat mode is selected

packages/editor/src/toolbar/components/split-button.tsx
This fixes one of the issues reported in #2330
=> All toolbars should scroll if buttons overflow

apps/mobile/app/components/launcher/index.js, apps/mobile/app/hooks/use-app-events.js, apps/mobile/app/screens/editor/tiptap/use-editor.ts, apps/mobile/app/screens/editor/wrapper.js, apps/mobile/app/services/notifications.ts, apps/mobile/native/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java, apps/mobile/share/store.js
Reload the editor if rendered view is lost and WebView messaging is not functional.
Closes #2420
Closes #2425
Closes #2422
=> mobile: reload editor if rendered view lost

apps/mobile/app/components/auth/session-expired.js, apps/web/src/views/auth.tsx
=> Obfuscate short emails

apps/web/src/utils/page-visibility.ts
Page Visibility API is not really reliable and even network change events don't work on all platforms and in all cases. Window Focus Events seem to be a much more reliable and foolproof way to handle this.
Closes #2367
=> Try to reconnect sync on window focus

apps/mobile/app/screens/editor/index.tsx, apps/mobile/app/screens/editor/loading.js, apps/mobile/app/screens/editor/tiptap/use-editor.ts, apps/mobile/app/screens/editor/tiptap/utils.ts
A second attempt to ensure editor is reloaded if it gets terminated in background or foreground by the OS on iOS devices.
=> Fix editor not rendered when enter foreground

extensions/web-clipper/src/content-scripts/all.ts, extensions/web-clipper/src/content-scripts/nn.ts
Webclipper creates many duplicate notes on when clipping websites. This fixes it by ensuring only one listener is attached with Notesnook App & the website.
Closes #2604
=> clipper: fix duplicate notes created on save

packages/editor/src/extensions/code-block/highlighter.ts
=> Prevent unintentional note saving on open

apps/mobile/app/screens/settings/functions.js, apps/mobile/app/screens/settings/picker/index.tsx, apps/mobile/app/screens/settings/picker/pickers.jsx, apps/mobile/app/screens/settings/settings-data.tsx, apps/web/src/dialogs/settings/backup-export-settings.ts
Added verification prompts in the following places:
1. Turning off encrypted backups (turning on encryption is a safe operation)
2. Exporting all notes
3. Turning on automatic backups if backups encryption is turned off
Additionally, removed password verification when creating a manual backup if encryption is _**on**_ as its a safe operation and poses no risk.
=> mobile: add verification prompts

packages/editor/src/extensions/code-block/component.tsx
- Fix selection colors in code block
- Improved UI of language selection popup
- Language aliases will now be upper case
=> editor: fix code-block ui

packages/editor/package-lock.json, packages/editor/package.json, packages/editor/src/extensions/image/component.tsx, packages/editor/src/toolbar/popups/image-upload.tsx, packages/editor/src/types.ts, packages/editor/src/utils/downloader.ts
=> Fix images not loading on paste

apps/web/src/components/auth-container/index.jsx
Added the _target and rel fields which will open the link in a new tab. 
Fixes issue #3856
=> fix: (#3856) link issue fixed

apps/web/src/components/editor/index.tsx, apps/web/src/stores/editor-store.ts
The issue was that the "readonly" and "locked" states were being branched by the type of session object. Therefore, we were not able to check the read only when the type was "locked". So, we modified the read only to be branched according to the value of session.note.read only when it is locked.
1. When locked, we added a readonly branch.
2. I added a type accordingly.
=> web: add readonly branch even in locked notes

apps/mobile/app/screens/settings/settings-data.tsx, apps/web/src/dialogs/settings/sync-settings.ts
- I noticed the explanation of force push is misdescribed in the mobile version, it has the same explanation as for force pull
- There's a spelling mistake I noticed being made `with whatever is one` that I fixed => `with whatever is on`
- I rephrased the wording to clarify when the buttons need to be pressed and what happens:
from: `Use this if some changes from this device are not appearing on other devices.`
to: `Use this if changes made on this device are not appearing on other devices.`
and:
from: `This will pull everything from the server and overwrite with whatever is one this device.`
to: `This will overwrite the data on this device with the latest data from the server.`
- I noticed on mobile it only shows `These must only be used for troubleshooting...` between pull sync and push …
=> global: clarify explanations for force push and force pull

apps/mobile/native/android/app/build.gradle
Changing `minSdk` version to `23` results in an increase in APK size due to uncompressed .so bundled instead the apk size resulting in a bigger apks for download. We revert this size increase for github and fdroid apk releases.
=> mobile: Fix apk size increase in v3.0.13

docs/help/contents/publish-notes-with-monographs.md
"URL" was spelled in lowercase, so I made them all uppercase
=> Capitalize all instances of "URL" in Monograph help page

docs/help/contents/faqs/is-there-an-eta.md
docs(help): Fix typo in is-there-an-eta.md - unnecessary was incorrectly spelled
Signed-off-by: Stephen Argent <stevesbrain@users.noreply.github.com>
=> docs(help): Fix typo in is-there-an-eta.md

packages/clipper/src/styles.ts, packages/clipper/src/utils.ts
Added a safe querySelector method to handle invalid selectors safely.
Closes #4697
=> Add safe querySelector method

packages/clipper/src/index.ts
Clipped images for free users never get uploaded and ultimately give errors every time note with the clipped data is opened. We disable clipping images for free users.
=> Add images only for pro users in clipper

apps/web/src/dialogs/issue-dialog.tsx
- EDIT: Previously, the message returned a string enclosed in `` with fixed spacing/new lines. This has been changed to be concatenated with `+` s so that a ```<p />``` is generated instead of a `pre` which was causing the fixed width and ugly scroll issue
- Fixes #5559
=> Fix bug report confirmation dialog width and scroll

apps/web/src/components/editor/action-bar.tsx, apps/web/src/components/editor/index.tsx, apps/web/src/components/editor/table-of-contents.tsx, apps/web/src/components/properties/index.tsx, apps/web/src/stores/editor-store.ts
* move toc button out of action bar into fixed position
* adjust editor width based on toc state
* save toc state in local storage
* increase indentation in toc
Signed-off-by: Zulfiqar Ali <85733202+01zulfi@users.noreply.github.com>
Closes #4977 
Closes #6711
=> web: changes related to table of contents (#4977)

packages/editor-mobile/src/components/statusbar.tsx, packages/editor/src/extensions/keep-in-view/keep-in-view.ts
- This also fixes an issue where scrolling up and down even a single px will make the statusbar keep toggling. now added a safe threshold
Closes [#5700](https://github.com/streetwriters/notesnook/issues/5700)
=> Fix selection scrolls to incorrect position on focus and press enter on mobile

packages/editor/src/toolbar/tools/link.tsx
Signed-off-by: Zulfiqar Ali <85733202+01zulfi@users.noreply.github.com>
Closes #6642
=> web: fix copy link button copying link text instead of link (#6642)

packages/editor/src/extensions/link/link.ts, packages/editor/src/extensions/link/tests/__snapshots__/link.test.ts.snap, packages/editor/src/extensions/link/tests/link.test.ts
* don't include empty square brackets in link
* handle multiple markdown links during pasting
Closes #6639
=> editor: fix markdown link pasting (#6639)

packages/editor/patches/@tiptap+extension-list-keymap+2.6.6.patch, packages/editor/src/extensions/list-item/tests/__snapshots__/list-item.test.ts.snap, packages/editor/src/extensions/list-item/tests/list-item.test.ts, packages/editor/test-utils/index.ts
* fix hitting backspace inside the second (or next) p in list item deleted the formatting of the entire list item
Closes #6712
=> editor: fix backspace deleting formatting in list item (#6712)

apps/monograph/app/routes/api.version.ts
Fix `/api/version` endpoints cors and fix `Response.json()` is not function.
=> monograph: fix monograph version endpoints cors

apps/web/src/dialogs/settings/index.tsx
Note: apart from the reported issue, this bug was present in other setting items as well for example in the "Authentication" and "Sync" tabs.
Closes #6909
=> web: fix setting item width (#6909)

apps/monograph/app/entry.server.tsx
when no charset is specified, Chinese notes will be garbled. Add default charset.
=> monograph: add monograph response charset header

apps/web/src/components/editor/tiptap.tsx
Zoom steps are always in increments of 10 when using a mouse wheel or trackpad.
Running `npm run prettier` as directed in the contributing guidelines modified many files, and I included them in this PR. Should I not run this command?
=> web: Fix inconsistent zoom amount when adjusting with scroll wheel.

apps/web/src/views/auth.tsx
* they overlap with the resend button
=> web: remove arrow buttons in mfa code input

packages/editor/src/toolbar/tools/link.tsx
I noticed that when a note is in read only mode, the `edit link` button is still showing up and the link can be edited.
I added the same line to the `EditLink` function as in `RemoveLink`
=> editor: hide edit button when in read only mode

apps/web/src/common/index.ts, apps/web/src/stores/editor-store.ts
This fixes the issue mentioned in #5202 by checking if an empty note already exists and if so, just setting the focus on the existing empty note instead of creating a new one when clicking the add note button.
=> editor: prevent creation of multiple empty notes

apps/web/src/dialogs/settings/components/importer.tsx
I noticed that for some dark themes the link was hard to read, so I made the color align with the current theme.
=> theme: make link color align with theme

apps/web/__e2e__/vault.test.ts, apps/web/src/components/status-bar/index.tsx, packages/core/src/api/vault.ts
=> Fix vault unlock status not shown when a note was unlocked

apps/web/__e2e__/editor.test.ts, apps/web/src/components/editor/action-bar.tsx, apps/web/src/components/editor/index.tsx, apps/web/src/components/editor/tiptap.tsx, apps/web/src/stores/editor-store.ts
=> web: add go to next/previous tab shortcut

apps/web/src/dialogs/prompt.tsx, apps/web/src/dialogs/settings/components/user-profile.tsx
* escaping or canceling the dialog would set profile's name to undefined
Closes #5947
=> web: fix edit profile name dialog

apps/web/src/dialogs/settings/index.tsx
=> web: use snarkdown to render setting item descriptions

packages/core/src/utils/title-format.ts
`DATE_TIME_STRIP_REGEX` should strip `.,/` characters.
Closes #7310
=> core: fix DATE_TIME_STRIP_REGEX

packages/editor/src/extensions/image/component.tsx
Clamped image size is bigger than the editor's width resulting in image and it's resizer frame having different sizes.
=> editor: fix clamped image size is larger than editor's width

apps/mobile/app/components/dialog/base-dialog.tsx, apps/mobile/app/components/ui/sheet/index.js, apps/mobile/app/screens/editor/tiptap/picker.ts
=> mobile: fix selecting image from gallery when applock is on

packages/editor-mobile/src/hooks/useEditorController.ts
Always load note's content if a load request is received in editor. Closes #7278
=> mobile: always load note content in editor

apps/web/src/components/split-pane/index.tsx
Fixes: #7335
This should also fix #7393 since the same functionality is used when toggeling the subnotebook folder.
=> web: fix nav menu collapse

packages/editor/src/toolbar/popups/link-popup.tsx, packages/intl/locale/en.po, packages/intl/locale/pseudo-LOCALE.po, packages/intl/src/strings.ts
The popup that appears when you want to edit a link, seemed a bit unintuitive, as you only saw the link in an input field twice:
Only the placeholders of the inputs suggested what is meant, so I added labels describing the fields:
=> editor: added link popup description

packages/editor/src/extensions/task-list/task-list.ts, packages/editor/src/extensions/task-list/utils.ts
Fixes: #7269
And this implements the desired functionality of not updating the stats for nested task lists, as described in the comments of the code.
=> editor: fix task-list stats

apps/vericrypt/src/components/errors-list.tsx, apps/web/at-rest-encryption.md, apps/web/src/common/sqlite/VFS.js, apps/web/src/common/sqlite/sqlite-types.ts, apps/web/src/dialogs/settings/index.tsx, apps/web/src/utils/stream-saver/mitm.ts
Found via `codespell -q 3 -D ../dictionary.txt -S "*.patch,*.po" -L actualy,childs,modifer,ontext,ontop,ony,recieved,reciever,se,seperator,te`
=> web: fix various typos

apps/web/src/common/key-map.ts, apps/web/src/stores/editor-store.ts
* add desktop shortcuts: ctrl+w, ctrl+shift+w. ctrl+n, ctrl+t, ctrl+tab, ctrl+shift+tab
Closes #6250 
Related to #4828 #1014
=> web: add tab keyboard shortcuts

apps/web/src/components/status-bar/index.tsx
Fixes: #7467
This makes the status-bar also visible on medium sized screens.
On small screens it is probably not necessary, since enabeling "focus mode" or "editor marings" does not make sense here.
=> web: fix status-bar disappearing

apps/mobile/app/components/list-items/note/index.tsx, apps/mobile/app/components/list-items/selection-wrapper/back-fill.tsx, apps/mobile/app/navigation/tabs-holder.js, apps/mobile/app/screens/editor/tiptap/commands.ts, apps/mobile/app/screens/editor/tiptap/picker.ts, apps/mobile/app/screens/editor/tiptap/use-tab-store.ts, apps/mobile/app/services/backup.ts
Fixed various typescript errors found when running `npx tsc --noEmit`
=> mobile: fix ts errors

packages/common/src/utils/tab-session-history.ts
If a note for a session is not found, we should remove the last sessionId in history.
=> Remove last session from history

packages/editor/src/extensions/code-block/component.tsx
Fixes: https://github.com/streetwriters/notesnook/issues/7284
This PR adds support for selecting the programming language by pressing the Enter key.
=> web: selecting the programming language by pressing Enter key

packages/editor/src/extensions/embed/component.tsx, packages/editor/src/extensions/image/component.tsx, packages/editor/src/toolbar/popups/embed-popup.tsx
This fixes a potential security vulnerability where pasting unknown content into the editor could create an RCE risk.
This PR fixes two issues:
1. Potential RCE when pasting/inserting an `iframe` containing a `javascript` link.
2. Potential RCE when pasting/inserting an `svg` containing JavaScript (why do SVGs allow JS in the first place?).
Mitigations include disallowing all execution of JS inside an SVG by rendering it in a sandboxed `iframe`. While we cannot disallow JS execution in embeds (that would break all embeds like YouTube videos), we have disallowed access to the parent window to all `iframe`s, again, by using a sandboxed `iframe` and by disallowing embedding of `javascript:` links.
To be clear, both of these issues can only be triggered when pasting/importing untrusted …
=> Fix potential RCEs when pasting unknown content into the editor

packages/editor/src/extensions/search-replace/search-replace.ts
The current search algorithm while accumulating text assumes that the text nodes are always followed by a paragraph node with endPos == textNode.endPos + 1. This is not true for complex text elements like tables where the endPos can be higher. Thus the start,end offsets of TextNodesWithPosition start getting off and results in incorrectly highlighted search results.
To fix this, simplify the TextNodesWithPosition to only hold start position and offset since startPos is always correct. We can calculate the end position on the fly by simply adding text length to startPos.
Issue #7431
=> editor: Fix search in complex text elements

packages/editor/src/extensions/embed/component.tsx
This PR fixes youtube and other embeds by allowing `allow-same-origin` in the iframe sandbox ONLY if the source url is an http or https url.
=> editor: fix youtube embeds

packages/editor/package-lock.json, packages/editor/package.json, packages/editor/src/extensions/clipboard/clipboard-dom-parser.ts, packages/editor/src/extensions/clipboard/clipboard-text-parser.ts, packages/editor/src/extensions/clipboard/tests/clipboard-text-parser.test.ts
Closes #3313
This PR adds support for pasting plain text as markdown. The logic works by running some heuristics on the pasted content to detect whether it is Markdown or not. If it is, it gets automatically converted to Markdown and pasted. This behavior can be bypassed by using `Paste without formatting`.
=> Add support for pasting as markdown

apps/monograph/Dockerfile
fix arm64 compatibility issue
--platform=$BUILDPLATFORM will overwrite buildx settings
reference:
https://github.com/streetwriters/notesnook/issues/6887
=> Update monograph Dockerfile

apps/web/src/components/editor/title-box.tsx
* wrap note title if it overflows
* remove auto-resizing of note title based on its length
=> web: wrap & remove auto-resize of note title

packages/ui/src/utils/position.ts
* position.top wasn't calculated correctly for the out of screen height case for non-mouse target
=> ui: fix submenu position

apps/web/src/app.tsx, apps/web/src/common/constants.ts, apps/web/src/components/status-bar/index.tsx
* current position would overlap slightly with the status bar, this commit moves the toast a little higher so it doesn't overlap
=> web: update toast position

apps/web/src/dialogs/command-palette/command-palette-dialog.tsx, apps/web/src/dialogs/command-palette/commands.ts, packages/core/src/api/lookup.ts, packages/core/src/utils/__tests__/fuzzy.test.ts, packages/core/src/utils/fuzzy.ts
* core: add getIdentifier in fuzzy; this allows the caller to provide a custom indentifier instead of relying on id field in the items list
* fix crashing when hitting enter when no results found
* fix commands list not refreshing when removing recent command
* fix recent command not showing up in the commands list
* fix searched commands showing up under wrong group label
Closes #7666 
Closes #7667
=> web: command palette fixes

packages/editor/src/extensions/image/component.tsx, packages/editor/styles/styles.css
In read-only mode, the resizer is removed causing the image to lose padding when line spacing is set to "single".
Closes #7741
=> editor: fix image padding in readonly mode

packages/editor/styles/styles.css
This pull request includes a small change to the `styles.css` file. The change adds a new CSS rule to ensure consistent space between heading and first element in callout
Closes #7738
=> editor: ensure consistent gap between heading and first element in callout

apps/web/src/app.tsx, apps/web/src/components/list-container/index.tsx, apps/web/src/components/navigation-menu/index.tsx, apps/web/src/components/notebook/index.tsx, apps/web/src/components/tag/index.tsx, apps/web/src/stores/app-store.ts
* when a nav item was clicked, list pane was removed entirely which made it difficult to re-open it, now when nav item is clicked we manually collapse, expand, or reset the list pane
* open list pane if 'reveal in list' is called
* open list pane if navigated to a different nav item
=> web: fix list pane not expanding

apps/mobile/app/common/filesystem/io.ts, apps/mobile/app/services/backup.ts
Backups fail if some of the attachments are downloaded but exist in AppGroup instead of app's own cache folder
=> Fix creating backups ios

apps/web/src/components/editor/index.tsx
=> web: don't remove properties pane when editor is refocused

apps/web/__e2e__/tabs.test.ts, apps/web/src/components/note/index.tsx, apps/web/src/stores/editor-store.ts
* fix pinned tab not working after page reload
* fix note opening in new tab even if its tab is present when active note is pinned
Closes #7683
=> web: pinned tab fixes

apps/web/__e2e__/editor.test.ts, apps/web/__e2e__/models/settings-view.model.ts, apps/web/src/components/editor/title-box.tsx, docs/help/contents/rich-text-editor/personalizing-rich-text-editor.md, packages/core/__tests__/notes.test.ts, packages/core/src/collections/notes.ts, packages/core/src/content-types/tiptap.ts, packages/core/src/database/index.ts, packages/core/src/database/migrations.ts, packages/core/src/types.ts, packages/core/src/utils/constants.ts, packages/core/src/utils/html-parser.ts, packages/core/src/utils/title-format.ts, packages/intl/locale/en.po, packages/intl/locale/pseudo-LOCALE.po
* when title format is set to $headline$, keep generating headline title until user manually edits the title
* extract headline from first html tag with content rather than first paragraph
Related to #7710 
Related to #6806 
Related to #3439 
Closes #5898
Closes #6378  
Closes https://github.com/streetwriters/notesnook/issues/4829
=> core: generate headline title until user edit && update headline extraction

packages/core/src/api/lookup.ts
* ids and items had different orders
Closes #7907
=> core: fix notes search results having mismatched references

apps/web/src/app.tsx
Closes #7884 
I think there's some room for the nav & list panes to have lesser width before snapping. For the list pane, the UI still breaks a little at `120`, but still usable. We should let the user decide if they want to go to this width. 
Anything lesser than these widths, the UI breaks a lot. This is where we can step in and not allow the user to go to this width (i.e. snap the pane)
=> web: reduce snapSize of nav & list panes

apps/mobile/app/screens/editor/tiptap/use-editor-events.tsx, packages/editor-mobile/src/components/tiptap.tsx, packages/editor-mobile/src/hooks/useEditorController.ts, packages/editor/src/extensions/keep-in-view/keep-in-view.ts
Fix cursor renders at wrong position on ios when tying long texts.
=> mobile: fix cursor bug on ios

apps/desktop/package-lock.json, apps/desktop/package.json
Closes #7949 
Closes #7604 
Both outline list and callout use `getBoundingClientRect` method in the collapse/expand arrow click handler. When editor zoom level was not 100%, this caused the `getBoundingClientRect` method to return different values than expected, though I'm not sure what the exact issue is. According to this thread, https://issues.chromium.org/issues/41461010 the fix was pushed in chromium v128.
This PR upgrades electron to v34.0.0 which is the last supported electron version and has chrome v132: https://www.electronjs.org/docs/latest/tutorial/electron-timelines. This fixes the outline list and callout expand/collapse bugs
=> desktop: upgrade electron to v34.0.0

apps/web/src/dialogs/command-palette/command-palette-dialog.tsx
* open new tab when query empty
* use editor-store methods for note creation
=> web: fix note create option in quick open dialog

packages/core/src/api/lookup.ts, packages/core/src/utils/query-transformer.ts
This PR adds support for searching based on fields. Currently, only the following fields are supported:
- `content:`
- `title:`
- `favorite:`
- `pinned:`
- `locked:`
- `archived:`
- `tag:`
- `color:`
- `edited_after:`
- `created_after:`
- `created_before:`
- `edited_before:`
=> Field based search

packages/editor/src/toolbar/tools/link.tsx
Closes https://github.com/streetwriters/notesnook/issues/8505
=> editor: don't show open & copy tools for empty links

apps/mobile/app/components/auth/common.js, apps/mobile/app/components/auth/index.js, apps/mobile/app/components/list-items/search-result/index.tsx, apps/mobile/app/components/sheet-provider/index.js, apps/mobile/app/components/sheets/user/index.tsx, apps/mobile/app/components/ui/sheet/index.js, apps/mobile/app/navigation/navigation-stack.tsx, apps/mobile/app/screens/editor/tiptap/use-editor-events.tsx, apps/mobile/app/screens/editor/tiptap/use-editor.ts, apps/mobile/app/services/navigation.ts, apps/mobile/patches/@react-navigation+core+6.4.8.patch
Reset navigation in `onStateChange` callback to prevent invalid state.
Closes #8511
=> mobile: fix resetting navigation

apps/mobile/app/hooks/use-is-floating-keyboard.ts, apps/mobile/patches/react-native+0.77.2.patch
Content does not shift upwards when Keyboard is opened on iPad when using iOS Split View.
=> Fix keyboard in iPad split view

apps/web/src/components/status-bar/index.tsx
=> web: fix update & vault status items vertical alignment
